"""Writes the rain seed SQL files from the cached Open-Meteo pulls (offline, deterministic).

Run: python3 ml/seed_rainfall_hourly.py
  supabase/seed/rainfall_hourly.sql           <- ml/data/openmeteo_2026-07.json (744 h, observed/reanalysis)
  supabase/seed/rainfall_context_2026_06.sql  <- ml/data/openmeteo_2026-06.json (720 h -> rainfall_hourly + 30 daily sums -> rainfall_daily)
  supabase/seed/rain_forecast_hourly.sql      <- ml/data/openmeteo_histforecast_2026-06-07.json (1464 h, Jun-Jul historical forecast)
Open-Meteo returns local (Asia/Manila, +08:00) timestamps without offset; we store them with +08:00.
(rainfall_daily.sql for July is generated by ml/simulate_july.py, not here.)
"""
import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(name: str, n: int):
    src = json.loads((ROOT / "ml/data" / name).read_text())
    times, mm = src["hourly"]["time"], src["hourly"]["precipitation"]
    assert len(times) == len(mm) == n, (name, len(times))
    assert src.get("utc_offset_seconds") == 28800
    assert all(p is not None and p >= 0 for p in mm), name
    return times, mm


def hourly_rows(times, mm, source):
    return [f"  ('{t}:00+08',{float(p)!r},'{source}')" for t, p in zip(times, mm)]


# July observed hourly
times, mm = load("openmeteo_2026-07.json", 744)
rows = hourly_rows(times, mm, "open-meteo")
(ROOT / "supabase/seed/rainfall_hourly.sql").write_text(
    "-- REAL hourly rainfall for Catbalogan (Open-Meteo, cached in ml/data/openmeteo_2026-07.json). Re-runnable.\n"
    "-- Generated by ml/seed_rainfall_hourly.py; used by the disruption-predictor (rain_24h/72h/14d/30d).\n"
    "insert into rainfall_hourly (ts, precipitation_mm, source) values\n"
    + ",\n".join(rows)
    + "\non conflict (ts) do nothing;\n"
)
print(f"rainfall_hourly.sql: {len(rows)} rows")

# June context (so Jul 1 rain windows / days-since-rain / 30 d sums are complete)
jt, jm = load("openmeteo_2026-06.json", 720)
jrows = hourly_rows(jt, jm, "open-meteo")
daily: "OrderedDict[str, float]" = OrderedDict()
for t, p in zip(jt, jm):
    daily[t[:10]] = daily.get(t[:10], 0.0) + float(p)
assert len(daily) == 30
drows = [f"  ('{d}',{round(v, 1)!r},'open-meteo')" for d, v in daily.items()]
(ROOT / "supabase/seed/rainfall_context_2026_06.sql").write_text(
    "-- REAL June 2026 rainfall context for Catbalogan (Open-Meteo, ml/data/openmeteo_2026-06.json), so July rain windows are complete. Re-runnable.\n"
    "-- Generated by ml/seed_rainfall_hourly.py. Daily rows are Manila-day sums of the hourly rows, rounded to 0.1 mm.\n"
    "insert into rainfall_hourly (ts, precipitation_mm, source) values\n"
    + ",\n".join(jrows)
    + "\non conflict (ts) do nothing;\n\n"
    "insert into rainfall_daily (date, precipitation_mm, source) values\n"
    + ",\n".join(drows)
    + "\non conflict (date) do nothing;\n"
)
print(f"rainfall_context_2026_06.sql: {len(jrows)} hourly + {len(drows)} daily rows")

# Historical forecast (deterministic offline demo for forecast_rain_48h_mm)
ft, fm = load("openmeteo_histforecast_2026-06-07.json", 1464)
frows = hourly_rows(ft, fm, "open-meteo-historical-forecast")
(ROOT / "supabase/seed/rain_forecast_hourly.sql").write_text(
    "-- Hourly rain FORECAST for Catbalogan 2026-06-01..2026-07-31 (Open-Meteo historical-forecast API, ml/data/openmeteo_histforecast_2026-06-07.json). Re-runnable.\n"
    "-- Generated by ml/seed_rainfall_hourly.py; lets the disruption-predictor compute forecast_rain_48h_mm offline for demo as_of times.\n"
    "insert into rain_forecast_hourly (ts, precipitation_mm, source) values\n"
    + ",\n".join(frows)
    + "\non conflict (ts) do nothing;\n"
)
print(f"rain_forecast_hourly.sql: {len(frows)} rows")
