-- 57 barangays of Catbalogan City (official PSA PSGC names, via PhilAtlas, checked 2026-10-06). Upsert: re-runnable, renames reach the remote.
-- 26 served by CWD (WSP p.8; service_level level_iii/level_i) + 31 unserved (outside the piped network; PSGC list, no WSP data).
-- `name` = official PSGC name; `wsp_name` = the WSP spelling where it differs (search alias). Ids are stable.
-- Coordinates of served rows are approximate OpenStreetMap (Nominatim) centroids, not survey data; unserved rows have none (NULL).
-- Household counts are unknown (not in the WSP): NULL. zone is NULL: the p.17 zoning map (Fig. 4.0)
-- has no barangay labels, so membership cannot be read from it.
insert into barangays (barangay_id, name, wsp_name, lat, lng, piped_households, unpiped_households, coverage_source, zone, service_level) values
  ('poblacion-01', 'Poblacion 1 (Barangay 1)', 'Poblacion 1', 11.7793566, 124.8809802, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-02', 'Poblacion 2 (Barangay 2)', 'Poblacion 2', 11.7781747, 124.8818049, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-03', 'Poblacion 3 (Barangay 3)', 'Poblacion 3', 11.7762421, 124.8797517, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-04', 'Poblacion 4 (Barangay 4)', 'Poblacion 4', 11.7752359, 124.880791, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-05', 'Poblacion 5 (Barangay 5)', 'Poblacion 5', 11.7744146, 124.8808816, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-06', 'Poblacion 6 (Barangay 6)', 'Poblacion 6', 11.7733767, 124.8814669, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-07', 'Poblacion 7 (Barangay 7)', 'Poblacion 7', 11.7735129, 124.8831998, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-08', 'Poblacion 8 (Barangay 8)', 'Poblacion 8', 11.770344, 124.8825688, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-09', 'Poblacion 9 (Barangay 9)', 'Poblacion 9', 11.7672978, 124.8832018, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-10', 'Poblacion 10 (Barangay 10)', 'Poblacion 10', 11.7786172, 124.8842388, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-11', 'Poblacion 11 (Barangay 11)', 'Poblacion 11', 11.7774794, 124.8844722, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-12', 'Poblacion 12 (Barangay 12)', 'Poblacion 12', 11.7761342, 124.8849875, null, null, 'unknown', null, 'level_iii'),
  ('poblacion-13', 'Poblacion 13 (Barangay 13)', 'Poblacion 13', 11.7783032, 124.8868396, null, null, 'unknown', null, 'level_iii'),
  ('san-andres', 'San Andres', null, 11.7874037, 124.8971854, null, null, 'unknown', null, 'level_iii'),
  ('canlapwas', 'Canlapwas (Poblacion)', 'Canlapwas', 11.782208, 124.8894566, null, null, 'unknown', null, 'level_iii'),
  ('san-pablo', 'San Pablo', null, 11.7801379, 124.8826179, null, null, 'unknown', null, 'level_iii'),
  ('munoz', 'Muñoz (Poblacion 14)', 'Muñoz', 11.7807436, 124.8837274, null, null, 'unknown', null, 'level_iii'),
  ('mercedes', 'Mercedes', null, 11.782393, 124.8774376, null, null, 'unknown', null, 'level_iii'),
  ('maulong', 'Maulong', null, 11.7926482, 124.8660885, null, null, 'unknown', null, 'level_iii'),
  ('guindapunan', 'Guindaponan', 'Guindapunan', 11.7716403, 124.8880985, null, null, 'unknown', null, 'level_iii'),
  ('guinsorongan', 'Guinsorongan', null, 11.7581661, 124.8851083, null, null, 'unknown', null, 'level_iii'),
  ('bunu-anan', 'Bunuanan', 'Bunu-anan', 11.7540974, 124.8885802, null, null, 'unknown', null, 'level_iii'),
  ('darahuway-guti', 'Darahuway Gote', 'Darahuway Guti', 11.7490138, 124.8721063, null, null, 'unknown', null, 'level_i'),
  ('darahuway-dako', 'Darahuway Daco', 'Darahuway Dako', 11.7448201, 124.876064, null, null, 'unknown', null, 'level_i'),
  ('payao', 'Payao', null, 11.8033839, 124.862532, null, null, 'unknown', null, 'level_i'),
  ('lagundi', 'Lagundi', null, 11.7597601, 124.9053032, null, null, 'unknown', null, 'level_i'),
  ('albalate', 'Albalate', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('bagongon', 'Bagongon', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('bangon', 'Bangon', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('basiao', 'Basiao', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('buluan', 'Buluan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cabugawan', 'Cabugawan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cagudalo', 'Cagudalo', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cagusipan', 'Cagusipan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cagutian', 'Cagutian', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cagutsan', 'Cagutsan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('canhawan-gote', 'Canhawan Gote', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cawayan', 'Cawayan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('cinco', 'Cinco', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('estaka', 'Estaka', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('ibol', 'Ibol', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('iguid', 'Iguid', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('libas', 'Libas', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('lobo', 'Lobo', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('manguehay', 'Manguehay', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('mombon', 'Mombon', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('new-mahayag', 'New Mahayag', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('old-mahayag', 'Old Mahayag', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('palanyogon', 'Palanyogon', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('pangdan', 'Pangdan', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('pupua', 'Pupua', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('rama', 'Rama', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('san-roque', 'San Roque', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('san-vicente', 'San Vicente', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('silanga', 'Silanga', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('socorro', 'Socorro', null, null, null, null, null, 'unknown', null, 'unserved'),
  ('totoringon', 'Totoringon', null, null, null, null, null, 'unknown', null, 'unserved')
on conflict (barangay_id) do update set
  name = excluded.name,
  wsp_name = excluded.wsp_name,
  service_level = excluded.service_level;
