-- Backup water sources (spec 04 input). Generated by supabase/seed/gen_sources.py - do not hand-edit.
-- Upsert by id = uuid5(namespace uuid5(DNS,'sources.pia-waterback'), stable key); re-runnable. Research + citations: docs/backup_sources.md.
-- provenance: wsp = CWD 2022 WSP; osm = OpenStreetMap (Overpass 2026-10-06); placeholder = SIMULATED (is_simulated = true).
-- RUBRIC (ASSUMPTIONS, not measurements):
--   safety_score: refill station (treated, DOH-regulated) 0.9; LGU/BFP trucked chlorinated water 0.8; neighboring barangay on piped supply 0.85;
--                 communal chlorinated deep well (WSP) 0.7; untreated spring/open well 0.4.
--   travel_minutes: round trip on foot = round(2 x haversine(barangay centroid, source) x 1.3 detour / 4 km/h x 60), min 1.
--                   Trucking = fixed 10. In-barangay point with unknown location = 10 (default). Barangay centroid unknown (Nominatim miss) = 40 (default). Centroids are approximate OSM values (barangays.sql).
--   cost_php_per_unit (unit = one 5-gal container): refill = PHP 25 ESTIMATE (national range 25-35, no Catbalogan price found); trucked/communal/neighbor = 0.
-- The `name`/`source_ref` of every row says where its numbers come from.
insert into sources (id, barangay_id, name, type, safety_score, travel_minutes, cost_php_per_unit, active, provenance, source_ref, is_simulated, lat, lng) values
  -- osm:aquaquest:albalate
  ('d3a0feaf-ecbe-59b0-877f-c49446fd437f', 'albalate', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 407, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x10.43km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:albalate
  ('75894bd3-3eb7-5c36-a3c8-a0ae0ca2012c', 'albalate', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 345, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (8.84 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:albalate
  ('09702d03-4f8d-529d-a92c-fbf3a683efc7', 'albalate', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:bagongon
  ('5cf6dfac-e518-5a48-a21c-13629a922b60', 'bagongon', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 767, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x19.67km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:bagongon
  ('2564cd69-2d9c-5da8-9312-e00e507e0d51', 'bagongon', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 693, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (17.78 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:bagongon
  ('208a4557-89a1-54a6-9c29-05864c27efe3', 'bagongon', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:bangon
  ('964b1589-a617-5fd4-9098-a280454d6619', 'bangon', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 438, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x11.23km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:bangon
  ('4ccfdf29-5783-5ae6-8543-dbf308304221', 'bangon', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 364, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (9.32 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:bangon
  ('120438ed-03ac-5aae-8cae-974e34f492a0', 'bangon', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:basiao
  ('7e771014-edbc-583c-8de6-3fe498e80e53', 'basiao', 'Aqua Blue Water Station', 'refill_station', 0.9, 359, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x9.20km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:basiao
  ('921b075f-9607-5497-b163-c3d77836db8a', 'basiao', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 282, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (7.23 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:basiao
  ('741dc348-2c37-5561-918f-cf4de596333a', 'basiao', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:buluan
  ('0da876c1-45df-532a-a1b7-af5054732b97', 'buluan', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 635, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x16.27km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:buluan
  ('3a8b5b3b-a18e-5411-9185-f4b93c349fbd', 'buluan', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 552, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (14.16 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:buluan
  ('3cc3e3e3-92f3-5d49-8fae-8498b004dcfb', 'buluan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:bunu-anan
  ('46e1f51a-1f8f-59d6-b1fe-c4817b2c53ab', 'bunu-anan', 'Aqua Blue Water Station', 'refill_station', 0.9, 77, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x1.98km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:bunu-anan
  ('aa99006b-1f7f-500d-b825-b840b2febdb7', 'bunu-anan', 'Neighboring barangay supply: Guinsorongan (simulated)', 'neighboring_barangay', 0.85, 23, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.59 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:bunu-anan
  ('c2344841-1b65-5f83-a00b-5cdf1c76f269', 'bunu-anan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cabugawan
  ('f6bbcd36-4eae-5df1-8d33-90a53a55dd35', 'cabugawan', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 287, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x7.37km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cabugawan
  ('7c8555f5-f255-5c29-a1b9-133e6a807eb0', 'cabugawan', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 192, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (4.92 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cabugawan
  ('abe6ec98-d38f-5cd4-b8b0-2283d0290b3d', 'cabugawan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cagudalo
  ('4f58e1ab-960a-5d3b-959c-67dd2938e8b8', 'cagudalo', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 347, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x8.90km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cagudalo
  ('c9e49cfa-8f80-525e-a62d-042809aed76a', 'cagudalo', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 273, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (7.01 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cagudalo
  ('d0ef72e6-5471-55c9-bf96-ab8824b17aa5', 'cagudalo', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cagusipan
  ('a96eb737-d097-5bcb-a1b7-e94e324122f4', 'cagusipan', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 597, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x15.32km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cagusipan
  ('f252fc56-0f8d-578b-b7f9-5c6b0c1476bc', 'cagusipan', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 526, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (13.48 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cagusipan
  ('15e29068-6ee4-5a04-9d29-9c94d6cdbeae', 'cagusipan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cagutian
  ('febdb809-c98c-5f97-8eae-1f0ee46d434e', 'cagutian', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 473, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x12.12km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cagutian
  ('56e3b612-19b0-5fb0-b117-c0fd0d641d6d', 'cagutian', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 404, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (10.37 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cagutian
  ('37e2d25c-c2f5-5fdd-b863-1782be211692', 'cagutian', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cagutsan
  ('10d8c100-bbb5-501f-94fd-a21cd58f3ae0', 'cagutsan', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 862, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x22.11km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cagutsan
  ('3b0a3e88-3e99-52e6-bffa-eb66280a31b4', 'cagutsan', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 784, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (20.10 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cagutsan
  ('8508c70c-48a9-55eb-a66d-05e91eaf0233', 'cagutsan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:canhawan-gote
  ('56badcb7-8146-53de-a9d5-3f3f21d0fa72', 'canhawan-gote', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 695, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x17.82km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:canhawan-gote
  ('9940c010-693e-5c3d-908e-993fcf534d45', 'canhawan-gote', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 611, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (15.67 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:canhawan-gote
  ('54399927-84cd-517a-91ae-ef7bd87e6ce4', 'canhawan-gote', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:canlapwas
  ('9b7dc7ec-2649-5b01-81ba-b2d50710f06b', 'canlapwas', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 47, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x1.21km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:canlapwas
  ('12d1c6ef-4539-56bd-80fd-86b445f2570b', 'canlapwas', 'Neighboring barangay supply: Poblacion 13 (Barangay 13) (simulated)', 'neighboring_barangay', 0.85, 20, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.52 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:canlapwas
  ('b3022e2a-6387-5050-ad2b-040050f29bda', 'canlapwas', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cawayan
  ('999851e3-8e8c-517f-807c-9cce152a20a5', 'cawayan', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 187, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x4.80km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cawayan
  ('e771883d-34a7-510a-a4a7-6eced6433b0d', 'cawayan', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 102, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (2.61 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cawayan
  ('29dafeb7-4dde-57b5-820c-494c5bfc7b29', 'cawayan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:cinco
  ('1fe4623f-977c-502d-8520-b684bd539f63', 'cinco', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 811, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x20.79km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:cinco
  ('a4efafdf-6030-55dd-b69c-2f552128a6cc', 'cinco', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 730, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (18.71 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:cinco
  ('ad96429d-b06b-5f9c-a5d2-6d711ef761fb', 'cinco', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:darahuway-dako
  ('fef42ef3-0a34-5803-9e38-e9e6bf4a02b2', 'darahuway-dako', 'Aqua Blue Water Station', 'refill_station', 0.9, 116, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.98km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:darahuway-dako
  ('5346583f-60a1-54e0-a63f-185b056d85b3', 'darahuway-dako', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 67, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.71 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:darahuway-dako
  ('9b985a8c-6ed3-5a24-8352-d8b22aa2a55f', 'darahuway-dako', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- wsp:cogao-darahuway-dako
  ('4b334641-ff78-5a67-9bee-c9e47fe2497d', 'darahuway-dako', 'Level I communal point via Cogao booster pump line - Darahuway Daco', 'communal_tap', 0.7, 10, 0, true, 'wsp', 'CWD 2022 WSP, printed p.14 s3.2.10 (Cogao booster, 2" x 1.7 km line to the two island barangays) + p.8/p.19 (Level I); point location not stated, in-barangay default 10 min; fed from the CWD network, so NOT independent of a Kulador failure', false, null, null),
  -- osm:aqua-blue:darahuway-guti
  ('e67ba80a-eb22-524e-9788-20fd85a8d547', 'darahuway-guti', 'Aqua Blue Water Station', 'refill_station', 0.9, 105, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.68km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:darahuway-guti
  ('62e6ea80-12ea-5455-9b1a-81bb15c9156c', 'darahuway-guti', 'Neighboring barangay supply: Guinsorongan (simulated)', 'neighboring_barangay', 0.85, 68, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.74 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:darahuway-guti
  ('e73f8a78-fac2-5bc9-a392-fae4c493a762', 'darahuway-guti', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- wsp:cogao-darahuway-guti
  ('60b193b4-9a66-5ee5-a13a-bdf75856050e', 'darahuway-guti', 'Level I communal point via Cogao booster pump line - Darahuway Gote', 'communal_tap', 0.7, 10, 0, true, 'wsp', 'CWD 2022 WSP, printed p.14 s3.2.10 (Cogao booster, 2" x 1.7 km line to the two island barangays) + p.8/p.19 (Level I); point location not stated, in-barangay default 10 min; fed from the CWD network, so NOT independent of a Kulador failure', false, null, null),
  -- osm:aquaquest:estaka
  ('419bfbb0-70fc-5dac-a622-4527a8b1750b', 'estaka', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 228, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x5.84km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:estaka
  ('bab2dc70-3ff5-5bea-b5aa-393f575b4ad3', 'estaka', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 143, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (3.67 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:estaka
  ('7d26bfa1-ad16-5b20-a0bd-0bec420b616f', 'estaka', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:guindapunan
  ('a0114230-1c04-57d0-ab8d-9eeff5bad6b8', 'guindapunan', 'Aqua Blue Water Station', 'refill_station', 0.9, 24, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.62km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:guindapunan
  ('609c32c1-70ea-5727-a9aa-30e44b69208b', 'guindapunan', 'Neighboring barangay supply: Poblacion 7 (Barangay 7) (simulated)', 'neighboring_barangay', 0.85, 22, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.57 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:guindapunan
  ('002b2afd-dfb8-5d2e-add6-0f80da78b3fc', 'guindapunan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:guinsorongan
  ('693a5bb5-f179-5f4e-b9c9-9234f813b0f7', 'guinsorongan', 'Aqua Blue Water Station', 'refill_station', 0.9, 56, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x1.45km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:guinsorongan
  ('531a3945-428f-57f8-bb29-39423d24de92', 'guinsorongan', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 23, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.59 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:guinsorongan
  ('226aa22a-2b9c-50d2-a2c1-d6dc151b5092', 'guinsorongan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:ibol
  ('953d54a0-7f53-52aa-822c-531781db97d4', 'ibol', 'Aqua Blue Water Station', 'refill_station', 0.9, 106, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.72km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:ibol
  ('47209594-1801-5a94-b5be-57099180c8df', 'ibol', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 55, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.41 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:ibol
  ('45e93212-6c34-53a6-838d-4ee16fdf07fa', 'ibol', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:iguid
  ('5e006536-0a98-5614-8c98-2154aaf086c7', 'iguid', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 302, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x7.75km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:iguid
  ('9b396ead-f385-54d3-a166-ca815c2c04a6', 'iguid', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 200, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (5.14 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:iguid
  ('8aba075b-b357-531a-9961-1c580abe6d37', 'iguid', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:lagundi
  ('40a170af-ff7e-585c-81a9-1487e1542a23', 'lagundi', 'Aqua Blue Water Station', 'refill_station', 0.9, 108, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.78km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:lagundi
  ('fa29865f-2ec3-5d89-819e-39c2925d5a07', 'lagundi', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 75, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.93 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:lagundi
  ('d78eec5f-5645-51a3-b1d1-eea5db20f067', 'lagundi', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- wsp:lagundi-barangay-hall-atm
  ('b4ea3bea-bc17-5239-a253-73ea5b6e9c71', 'lagundi', 'Lagundi barangay hall - ATM tubig machine (Level I)', 'communal_tap', 0.7, 10, 0, true, 'wsp', 'CWD 2022 WSP, printed p.14 s3.2.12 (''two ATMs installed in the pumping station and at barangay Hall''); exact location unknown, travel = in-barangay default 10 min', false, null, null),
  -- wsp:lagundi-deepwell-atm
  ('935e358c-a369-5900-9c01-07c083f82372', 'lagundi', 'Lagundi deep well pumping station - ATM tubig machine (Level I)', 'communal_tap', 0.7, 26, 0, true, 'wsp', 'CWD 2022 WSP, printed p.14 s3.2.12 (PDF p.19); coords from N11 45''43.7" E124 54''39.2"; 2HP pump, chlorinator, 2+1 m3 tanks; travel = haversine from centroid', false, 11.762139, 124.910889),
  -- osm:aquaquest:libas
  ('e41732a2-6a98-5e55-8b9e-1feebd97f332', 'libas', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 271, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x6.94km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:libas
  ('d2501290-edba-5ea5-b545-2a2f1f519b67', 'libas', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 213, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (5.47 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:libas
  ('718bce72-0271-5570-ba8a-440592c22839', 'libas', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:lobo
  ('855b8df0-d22c-545b-a90f-fc6fd4eeb675', 'lobo', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 308, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x7.91km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:lobo
  ('672ff72f-dabc-50da-a9d1-a87e6f559a98', 'lobo', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 229, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (5.87 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:lobo
  ('6b1ec88f-4e8f-5779-8b44-4b2e3ed94e51', 'lobo', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:manguehay
  ('85524147-2900-54b6-a14a-7c34ebcbffdf', 'manguehay', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 172, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x4.40km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:manguehay
  ('a8c6102b-6e45-5b41-8b27-a7ee1bff510d', 'manguehay', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 102, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (2.62 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:manguehay
  ('31238b67-5b1c-5364-aa32-f5f5f7bcf220', 'manguehay', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:maulong
  ('7618485b-db64-56fd-9ca6-308dce97136d', 'maulong', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 102, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.61km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:maulong
  ('c1e76ead-64e0-572e-b61f-c52fb51c2823', 'maulong', 'Neighboring barangay supply: Mercedes (simulated)', 'neighboring_barangay', 0.85, 66, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.68 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:maulong
  ('02a285af-4ae4-5069-9d33-c72ac6db0741', 'maulong', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:mercedes
  ('a249808d-b98c-5a5f-af97-778db992eee8', 'mercedes', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 38, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.97km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:mercedes
  ('e1900bff-9d43-510b-be20-46e920372e92', 'mercedes', 'Neighboring barangay supply: Poblacion 1 (Barangay 1) (simulated)', 'neighboring_barangay', 0.85, 20, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.51 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:mercedes
  ('5d552a21-5f16-589a-bd21-a62dedc16a2b', 'mercedes', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:mombon
  ('4db76c34-eb0b-5432-b6f7-0d878604b5af', 'mombon', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 788, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x20.20km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:mombon
  ('e3fd9251-25fc-50df-9875-7aaae5f6fc37', 'mombon', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 716, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (18.35 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:mombon
  ('08223e87-9c5b-5626-afe5-9d37a4cf6e0f', 'mombon', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:munoz
  ('941fc793-43c1-5a6a-b156-26c6f5246a38', 'munoz', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 28, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.72km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:munoz
  ('69dbc301-67cc-532e-9b48-bd1e5850689b', 'munoz', 'Neighboring barangay supply: San Pablo (simulated)', 'neighboring_barangay', 0.85, 5, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.14 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:munoz
  ('b87c8596-dfdf-5481-853e-35a0beb8197b', 'munoz', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:new-mahayag
  ('8474cd7e-1def-5596-b1fe-2b38a949d93a', 'new-mahayag', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 387, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x9.93km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:new-mahayag
  ('95ef7f07-f0b9-5ff6-94e2-69c7f89f1b64', 'new-mahayag', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 286, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (7.32 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:new-mahayag
  ('fd840af2-18a9-5926-b552-8531d100c760', 'new-mahayag', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:old-mahayag
  ('28f0b167-0b8c-513f-b986-8c13f59a387a', 'old-mahayag', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 399, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x10.24km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:old-mahayag
  ('9c3c670b-a7fb-5687-96eb-875301f6b8ea', 'old-mahayag', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 298, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (7.63 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:old-mahayag
  ('47a362d3-431d-520c-a814-5e22c8a9803f', 'old-mahayag', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:palanyogon
  ('0770f62b-0ffa-5571-9e48-cd505d4b8870', 'palanyogon', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 408, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x10.46km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:palanyogon
  ('6a9871ad-f558-5b7b-bf38-5ad82ac4e02e', 'palanyogon', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 324, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (8.31 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:palanyogon
  ('dccbf67e-3a3a-59fd-bb8b-78593fa08a84', 'palanyogon', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:pangdan
  ('defb5610-ceec-5263-bb89-ab87f6c0286d', 'pangdan', 'Aqua Blue Water Station', 'refill_station', 0.9, 189, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x4.84km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:pangdan
  ('af19f604-9d75-543d-aaf9-c4d56e1dae62', 'pangdan', 'Neighboring barangay supply: Bunuanan (simulated)', 'neighboring_barangay', 0.85, 130, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (3.34 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:pangdan
  ('9ce2b9d7-9793-55fc-8ca6-d5622c671377', 'pangdan', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:payao
  ('424ea4d6-2a20-5bb3-a6f0-b2ba0ab4d324', 'payao', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 148, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x3.80km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- osm:jetmatic-well:payao
  ('6f5c7144-e281-57eb-9e2f-ac7359da735b', 'payao', 'Jet Matic (Artesian Well), operator Est. Michael Baldemor Estrada', 'communal_tap', 0.4, 107, 0, true, 'osm', 'https://www.openstreetmap.org/node/3750592063 (man_made=water_well); assigned to nearest barangay WITH a known centroid, actual barangay unverified; low confidence; untreated/commercial status unknown', false, 11.8169126, 124.8413309),
  -- ph:neighbor:payao
  ('ba2d3dc7-2cde-52fc-9c97-68d1397b934e', 'payao', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 49, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.25 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:payao
  ('35a9baa8-a7d3-5ebf-8eae-dd90facb1556', 'payao', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- wsp:payao-deepwell
  ('cd5848d8-b220-59ca-b518-5644540eb805', 'payao', 'Payao deep well pumping station (1.5 L/s, 2x2 m3 tanks; built for LGU facilities)', 'communal_tap', 0.7, 21, 0, true, 'wsp', 'CWD 2022 WSP, printed p.14 s3.2.13 (PDF p.19); coords from N11 48''8.1" E124 52''2.2"; WSP says it supplies LGU facilities (relocation site, COVID facilities, govt offices); public access for residents unverified', false, 11.80225, 124.867278),
  -- osm:aquaquest:poblacion-01
  ('7aa2b49d-0877-5829-8917-947f0b94a834', 'poblacion-01', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 21, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.53km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-01
  ('4f14ddf3-edaf-574a-9f85-8aa0f4173dad', 'poblacion-01', 'Neighboring barangay supply: Poblacion 2 (Barangay 2) (simulated)', 'neighboring_barangay', 0.85, 6, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.16 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-01
  ('708f23ef-92b7-54e2-91ac-6ec9bd8b70ef', 'poblacion-01', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:poblacion-02
  ('35172a18-a39b-5af1-a25b-4c73795c18b9', 'poblacion-02', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 15, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.40km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-02
  ('a4e07fce-7fd3-506b-8a90-1a084fa3e5fc', 'poblacion-02', 'Neighboring barangay supply: Poblacion 1 (Barangay 1) (simulated)', 'neighboring_barangay', 0.85, 6, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.16 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-02
  ('ac3eb989-8ed0-54b3-9fe7-056f3977939a', 'poblacion-02', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-03
  ('e6cd67ac-4779-5f0c-9082-60246fcc8a78', 'poblacion-03', 'Aqua Blue Water Station', 'refill_station', 0.9, 26, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.66km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-03
  ('ba6f1331-262c-5738-8643-5350ffd8a92d', 'poblacion-03', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 10, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.26km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-03
  ('7013f8c1-e811-5533-8eaa-3e9e6de89c06', 'poblacion-03', 'Neighboring barangay supply: Poblacion 4 (Barangay 4) (simulated)', 'neighboring_barangay', 0.85, 6, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.16 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-03
  ('2e91e3f4-ef6d-5411-ae97-ee5819aa2b7f', 'poblacion-03', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-04
  ('bc032a01-4eca-5792-8537-6a299d706b3e', 'poblacion-04', 'Aqua Blue Water Station', 'refill_station', 0.9, 20, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.51km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-04
  ('e565c1dd-707b-540a-a7bc-74577797aa3b', 'poblacion-04', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 4, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.10km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-04
  ('9d624290-41e0-5e47-adde-5907f2709a00', 'poblacion-04', 'Neighboring barangay supply: Poblacion 5 (Barangay 5) (simulated)', 'neighboring_barangay', 0.85, 4, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.09 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-04
  ('788746de-5ad2-5921-b3fd-9347694e2fa1', 'poblacion-04', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-05
  ('3c86d72e-4c67-5f17-a03e-5632f84808cb', 'poblacion-05', 'Aqua Blue Water Station', 'refill_station', 0.9, 17, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.43km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-05
  ('0ff559e8-5df1-5fa9-b905-323320418f15', 'poblacion-05', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 3, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.06km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-05
  ('0a0f403a-2834-5ec3-820c-ccf4f6036e63', 'poblacion-05', 'Neighboring barangay supply: Poblacion 4 (Barangay 4) (simulated)', 'neighboring_barangay', 0.85, 4, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.09 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-05
  ('42753bfc-4a7f-57c1-93ec-3ccb91e248f8', 'poblacion-05', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-06
  ('7d544bf8-5366-54ea-8623-286198ee905b', 'poblacion-06', 'Aqua Blue Water Station', 'refill_station', 0.9, 12, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.30km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-06
  ('81055117-8792-5125-b577-78744cbec5f5', 'poblacion-06', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 5, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.14km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-06
  ('a3bb5b2e-a1c1-5bc9-aa28-4f06a804365d', 'poblacion-06', 'Neighboring barangay supply: Poblacion 5 (Barangay 5) (simulated)', 'neighboring_barangay', 0.85, 5, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.13 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-06
  ('2472e058-3333-556b-92a8-ce059074ac52', 'poblacion-06', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-07
  ('9ab38bdb-c2d0-562a-9205-ac03548c9b70', 'poblacion-07', 'Aqua Blue Water Station', 'refill_station', 0.9, 12, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.30km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-07
  ('4be2eb4c-dc41-5625-b897-66a4fcc9ebee', 'poblacion-07', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 9, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.23km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-07
  ('79484ca9-3e2f-5d91-ba10-a8aad8b9a845', 'poblacion-07', 'Neighboring barangay supply: Poblacion 6 (Barangay 6) (simulated)', 'neighboring_barangay', 0.85, 7, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.19 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-07
  ('28984434-2192-53ab-844f-d604116f320b', 'poblacion-07', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-08
  ('e8938d86-8855-53a2-84c8-7b80079f3eec', 'poblacion-08', 'Aqua Blue Water Station', 'refill_station', 0.9, 3, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.06km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-08
  ('b1bf1db1-7520-5cba-8744-5be214f9aaf4', 'poblacion-08', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 19, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.49km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:poblacion-08
  ('d828b9a1-af56-522e-a64f-9fd406609e17', 'poblacion-08', 'Neighboring barangay supply: Poblacion 9 (Barangay 9) (simulated)', 'neighboring_barangay', 0.85, 13, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.35 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-08
  ('cd08df1d-90c7-5f48-a93d-eeba20df912e', 'poblacion-08', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-09
  ('fc65619b-d0b1-5065-bdcc-33e346edfca4', 'poblacion-09', 'Aqua Blue Water Station', 'refill_station', 0.9, 16, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.41km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:poblacion-09
  ('c818ec0d-7bab-5396-86fb-5761f027f7e3', 'poblacion-09', 'Neighboring barangay supply: Poblacion 8 (Barangay 8) (simulated)', 'neighboring_barangay', 0.85, 13, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.35 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-09
  ('340e8fcc-9071-5125-97eb-aac65d428835', 'poblacion-09', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:poblacion-10
  ('5dbd497d-4dee-538d-b7ae-86707f0473f7', 'poblacion-10', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 21, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.54km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- osm:osm-well-9208545293:poblacion-10
  ('e2cf3925-e294-51cd-ba3a-d2b0f1294428', 'poblacion-10', 'Unnamed public-access well (OSM, pump 2-10 HP)', 'communal_tap', 0.4, 15, 0, true, 'osm', 'https://www.openstreetmap.org/node/9208545293 (man_made=water_well, access=permissive); untreated, quality unknown; travel from centroid', false, 11.7768125, 124.8872486),
  -- ph:neighbor:poblacion-10
  ('a16902ce-f3d5-5242-9c50-fb2735ae59af', 'poblacion-10', 'Neighboring barangay supply: Poblacion 11 (Barangay 11) (simulated)', 'neighboring_barangay', 0.85, 5, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.13 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-10
  ('fb3539db-8efe-5b3a-b807-299d6a9be105', 'poblacion-10', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-11
  ('22516712-6e65-5979-9bd3-aad1ae9bd921', 'poblacion-11', 'Aqua Blue Water Station', 'refill_station', 0.9, 30, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.76km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-11
  ('40f903e6-6fe2-55ff-9e91-11a51348066f', 'poblacion-11', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 18, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.46km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- osm:osm-well-9208545293:poblacion-11
  ('b4bf16db-c9a9-5139-abf9-f661d3be8f82', 'poblacion-11', 'Unnamed public-access well (OSM, pump 2-10 HP)', 'communal_tap', 0.4, 12, 0, true, 'osm', 'https://www.openstreetmap.org/node/9208545293 (man_made=water_well, access=permissive); untreated, quality unknown; travel from centroid', false, 11.7768125, 124.8872486),
  -- ph:neighbor:poblacion-11
  ('223e4065-4de1-5598-b8af-c3100f5ded4b', 'poblacion-11', 'Neighboring barangay supply: Poblacion 10 (Barangay 10) (simulated)', 'neighboring_barangay', 0.85, 5, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.13 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-11
  ('b3d1c6e1-a59c-50d0-b278-dfb079bbce5c', 'poblacion-11', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:poblacion-12
  ('4bae1e69-e6d5-5a79-8399-fc6621f1f8ff', 'poblacion-12', 'Aqua Blue Water Station', 'refill_station', 0.9, 25, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.64km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- osm:aquaquest:poblacion-12
  ('e106d2d9-dedc-5574-9fe1-2f573f930c1c', 'poblacion-12', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 16, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.42km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- osm:osm-well-9208545293:poblacion-12
  ('5dafec85-d839-51eb-84ab-754f920b70f0', 'poblacion-12', 'Unnamed public-access well (OSM, pump 2-10 HP)', 'communal_tap', 0.4, 10, 0, true, 'osm', 'https://www.openstreetmap.org/node/9208545293 (man_made=water_well, access=permissive); untreated, quality unknown; travel from centroid', false, 11.7768125, 124.8872486),
  -- ph:neighbor:poblacion-12
  ('bf1f5c56-f7ce-526e-bc62-7de9c175872b', 'poblacion-12', 'Neighboring barangay supply: Poblacion 11 (Barangay 11) (simulated)', 'neighboring_barangay', 0.85, 6, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.16 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-12
  ('91e20754-0e8d-53a9-9e1d-2a73a152bb05', 'poblacion-12', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:poblacion-13
  ('1abc26f4-b4f1-5166-b129-af66bd559584', 'poblacion-13', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 28, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.72km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- osm:osm-well-9208545293:poblacion-13
  ('aeb655d1-19ce-5b64-ae8c-9a649f4e189d', 'poblacion-13', 'Unnamed public-access well (OSM, pump 2-10 HP)', 'communal_tap', 0.4, 7, 0, true, 'osm', 'https://www.openstreetmap.org/node/9208545293 (man_made=water_well, access=permissive); untreated, quality unknown; travel from centroid', false, 11.7768125, 124.8872486),
  -- ph:neighbor:poblacion-13
  ('d8054582-ec6f-52ea-b4fb-05583bff3fde', 'poblacion-13', 'Neighboring barangay supply: Poblacion 11 (Barangay 11) (simulated)', 'neighboring_barangay', 0.85, 11, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.27 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:poblacion-13
  ('32fa2440-e968-50dc-938c-d4492415f70c', 'poblacion-13', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:pupua
  ('eebe10ff-9514-5262-ae78-9c185a3f21d2', 'pupua', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 184, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x4.71km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:pupua
  ('ee934ef5-424a-5e83-8746-9bcf0b8e8e51', 'pupua', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 86, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (2.19 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:pupua
  ('f0893864-1533-5361-a9d9-b57ef1152be0', 'pupua', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:rama
  ('c53c11bc-3a74-538f-93fd-168e18e2e2d4', 'rama', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 828, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x21.23km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:rama
  ('0dac7b16-4bbb-558d-8d1f-9584bfd3890f', 'rama', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 747, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (19.15 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:rama
  ('2c00059c-1107-563b-9ef7-ed661145de02', 'rama', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:san-andres
  ('d3dd3ed6-c28c-58f7-8b3e-ff342091b377', 'san-andres', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 87, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x2.23km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:san-andres
  ('29308ff4-4efa-5cc6-a815-9a85bc05fc29', 'san-andres', 'Neighboring barangay supply: Canlapwas (Poblacion) (simulated)', 'neighboring_barangay', 0.85, 40, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (1.02 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:san-andres
  ('cb584f9f-736b-55a4-a484-e95a46ac114a', 'san-andres', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:san-pablo
  ('263996c4-524d-5c37-8add-977d1ec81f7f', 'san-pablo', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 24, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x0.63km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:san-pablo
  ('0f36273c-385a-5303-b926-8997f40fb4ee', 'san-pablo', 'Neighboring barangay supply: Muñoz (Poblacion 14) (simulated)', 'neighboring_barangay', 0.85, 5, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.14 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:san-pablo
  ('ca05c819-9a0c-5b0b-86e3-fa3e889a8962', 'san-pablo', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:san-roque
  ('1ae2632a-679f-5e0e-bd08-e117be3b3b88', 'san-roque', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 221, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x5.67km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:san-roque
  ('27b4a27b-3571-5606-83f3-b9cf9381fd4a', 'san-roque', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 125, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (3.22 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:san-roque
  ('c3851c4c-529b-5a14-beca-83651553aa3e', 'san-roque', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:san-vicente
  ('1d8c75ee-1878-580a-be70-4cb073c0b943', 'san-vicente', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 448, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x11.49km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:san-vicente
  ('da9bca2b-3f21-5893-b51c-f29ab9fe1412', 'san-vicente', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 349, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (8.95 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:san-vicente
  ('d0f4e9e8-58c5-5151-8336-1ab605deac09', 'san-vicente', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:silanga
  ('d990abac-54a6-5269-ae0d-48886ea5c650', 'silanga', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 255, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x6.53km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:silanga
  ('f647a2a5-2264-530b-8381-a57ee8dfbb88', 'silanga', 'Neighboring barangay supply: Maulong (simulated)', 'neighboring_barangay', 0.85, 153, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (3.93 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:silanga
  ('1a5e00f3-4721-57ec-8792-b759fac96573', 'silanga', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aqua-blue:socorro
  ('3118be93-fad4-5fe9-a690-06d1032f9cd7', 'socorro', 'Aqua Blue Water Station', 'refill_station', 0.9, 46, 25, true, 'osm', 'https://www.openstreetmap.org/node/4721500289 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x1.17km x1.3 /4kmh', false, 11.770917, 124.8824883),
  -- ph:neighbor:socorro
  ('90ca9341-0cd8-5b4f-9532-c1e3e0b198cd', 'socorro', 'Neighboring barangay supply: Guindaponan (simulated)', 'neighboring_barangay', 0.85, 29, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (0.75 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:socorro
  ('6d1ee320-5221-5797-a5da-daba64d386a0', 'socorro', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null),
  -- osm:aquaquest:totoringon
  ('b23c2337-b1a2-5452-8230-38ec3e73e1cd', 'totoringon', 'Aquaquest.com refill station (Del Rosario St.)', 'refill_station', 0.9, 390, 25, true, 'osm', 'https://www.openstreetmap.org/node/3376469925 (Overpass 2026-10-06, shop=water); price = ESTIMATE PHP25/5gal; travel = 2x10.01km x1.3 /4kmh', false, 11.774634, 124.8814307),
  -- ph:neighbor:totoringon
  ('fc4335c4-197c-5d9c-a5b5-d8f7d1fa8f1d', 'totoringon', 'Neighboring barangay supply: San Andres (simulated)', 'neighboring_barangay', 0.85, 311, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): nearest other CWD Level III barangay by centroid (7.98 km); assumes it still has piped supply (not true in a plant-wide failure)', true, null, null),
  -- ph:truck:totoringon
  ('5a35513f-e03e-5de8-9095-3757ad45412f', 'totoringon', 'LGU water truck drop point (simulated)', 'trucking', 0.8, 10, 0, true, 'placeholder', 'Simulated placeholder (docs/backup_sources.md rubric): chlorinated LGU/BFP trucking 0.8, fixed 10 min to drop point, free; no real drop point list was found', true, null, null)
on conflict (id) do update set
  barangay_id = excluded.barangay_id, name = excluded.name, type = excluded.type, safety_score = excluded.safety_score,
  travel_minutes = excluded.travel_minutes, cost_php_per_unit = excluded.cost_php_per_unit, active = excluded.active,
  provenance = excluded.provenance, source_ref = excluded.source_ref, is_simulated = excluded.is_simulated, lat = excluded.lat, lng = excluded.lng;
