-- Spec 10: settlement clusters for need-based priority (Dev B, owner OK 2026-10-07; Dev A review pending).
-- people = PSA 2020 barangay total x the cluster's share of the WorldPop 2020 100 m grid
-- (cells assigned to the nearest barangay centroid; no boundary polygons). Data: supabase/seed/clusters.sql,
-- generated by data/population/build_clusters.py. Additive only; safe to run twice.

create table if not exists clusters (
  cluster_id text primary key,
  barangay_id text not null references barangays (barangay_id),
  label text not null,
  lat double precision not null,
  lng double precision not null,
  people integer not null check (people >= 0),
  people_source text not null default 'psa2020_x_worldpop2020'
);
create index if not exists clusters_barangay_idx on clusters (barangay_id);

-- Reference data, readable by the app like barangays and sources.
alter table clusters enable row level security;
drop policy if exists clusters_select_all on clusters;
create policy clusters_select_all on clusters for select to anon, authenticated using (true);

-- AllocationDecision.cluster_id (spec 10): which cluster a priority rank is for. Nullable; barangay_id stays.
alter table allocations add column if not exists cluster_id text references clusters (cluster_id);
