// SPEC: 08 — the one trilingual CopyKey table. Every user-facing string lives here.
// Rows are [key, english, filipino, waray]. {placeholders} are filled by t().
//
// REVIEW: every Waray string and every Filipino string is a draft by the dev team,
// not a native-speaker review. Spec 08 says flag, don't guess: they're all listed in
// NEEDS_REVIEW below until a fluent teammate checks them. English is the default
// language until then.
import { CopyKey } from "../contracts/spec08";

const ROWS = [
  // App shell
  ["app.name", "Tubig Patas", "Tubig Patas", "Tubig Patas"],
  ["app.saved_offline", "Saved on this phone · works without signal", "Naka-save sa phone na ito · gumagana kahit walang signal", "Naka-save hini nga phone · nagana bisan waray signal"],
  ["app.offline_stale", "No signal · showing what was saved at {time}", "Walang signal · ipinapakita ang naka-save noong {time}", "Waray signal · ginpapakita an naka-save han {time}"],
  ["app.loading", "Getting the latest status…", "Kinukuha ang pinakabagong balita…", "Ginkukuha an pinakabag-o nga kahimtang…"],
  ["app.error_title", "We can't reach Tubig Patas right now", "Hindi namin maabot ang Tubig Patas ngayon", "Diri namon maabot an Tubig Patas yana"],
  ["app.error_body", "Check your signal, then try again.", "Tingnan ang signal, saka subukan ulit.", "Kitaa an signal, katapos utroha."],
  ["app.retry", "Try again", "Subukan ulit", "Utroha"],
  ["app.updated_at", "Updated {time}", "Na-update {time}", "Gin-update {time}"],
  ["app.back", "Back", "Bumalik", "Balik"],

  // Resident bottom bar
  ["nav.status", "Status", "Status", "Kahimtang"],
  ["nav.sources", "Sources", "Mapagkukunan", "Kuhaan"],
  ["nav.history", "History", "Kasaysayan", "Kasaysayan"],

  // Water states (signal level → state, see lib/waterState.ts)
  ["state.flowing.chip", "Flowing", "Dumadaloy", "Nagawas"],
  ["state.flowing.headline", "Water is flowing", "May tubig", "May tubig"],
  ["state.flowing.sub", "Next planned work: none", "Susunod na nakaplanong trabaho: wala", "Sunod nga plano nga trabaho: waray"],
  ["state.headsup.chip", "Heads-up", "Paalala", "Pahinumdom"],
  ["state.headsup.headline", "Store water tonight", "Mag-ipon ng tubig ngayong gabi", "Pag-ipon hin tubig yana nga gab-i"],
  ["state.headsup.sub", "Likely to stop from {time}", "Posibleng mawala simula {time}", "Posible mawara tikang {time}"],
  ["state.interrupted.chip", "Interrupted", "Naputol", "Naputol"],
  ["state.interrupted.headline", "No water from the tap", "Walang tubig sa gripo", "Waray tubig ha gripo"],
  ["state.repair.chip", "Planned repair", "Nakaplanong ayos", "Plano nga pag-ayad"],
  ["state.repair.headline", "Off for a pipe repair", "Patay dahil sa pag-aayos ng tubo", "Patay kay ginaayad an tubo"],
  ["cause.turbidity", "The river is too muddy to treat after last night's rain.", "Sobrang labo ng ilog para linisin dahil sa ulan kagabi.", "Sobra kalubog an salog para limpyohan tungod han uran kagab-i."],
  ["cause.drought", "The river is too low to supply everyone.", "Masyadong mababa ang ilog para sa lahat.", "Sobra kahubas an salog para ha ngatanan."],
  ["cause.repair", "The pipes are being repaired.", "Inaayos ang mga tubo.", "Ginaayad an mga tubo."],
  ["cause_short.turbidity", "river too muddy to treat", "sobrang labo ng ilog", "sobra kalubog an salog"],
  ["cause_short.drought", "river too low", "masyadong mababa ang ilog", "sobra kahubas an salog"],
  ["cause_short.repair", "pipe repair", "pag-aayos ng tubo", "pag-ayad han tubo"],

  // Resident status card
  ["status.back_between", "Back today between", "Babalik ngayong araw sa pagitan ng", "Mabalik yana nga adlaw butnga han"],
  ["status.most_likely", "Most likely", "Malamang", "Posible gud"],
  ["status.now", "Now", "Ngayon", "Yana"],
  ["status.back", "Back", "Balik", "Balik"],
  ["status.scale_6am", "6 AM", "6 AM", "6 AM"],
  ["status.scale_noon", "Noon", "Tanghali", "Udto"],
  ["status.scale_6pm", "6 PM", "6 PM", "6 PM"],
  ["status.scale_12am", "12 AM", "12 AM", "12 AM"],
  ["status.next_update_by", "Next update by {time}", "Susunod na update bago mag-{time}", "Sunod nga update antes han {time}"],
  ["status.next_update_rest", ", even if nothing changes.", ", kahit walang pagbabago.", ", bisan waray pagbag-o."],
  ["action.store_water", "Store water", "Mag-ipon ng tubig", "Pag-ipon hin tubig"],
  ["action.find_water", "Find water", "Maghanap ng tubig", "Pangita hin tubig"],

  // Storage plan
  ["storage.title", "Store {litres} L for 24 hours", "Mag-ipon ng {litres} L para sa 24 oras", "Pag-ipon hin {litres} L para ha 24 oras"],
  ["storage.household", "For your household of {people} · {per} L per person", "Para sa pamilya ng {people} · {per} L bawat tao", "Para ha pamilya nga {people} · {per} L kada tawo"],
  ["storage.steps", "{done} of {total} steps done", "{done} sa {total} hakbang tapos na", "{done} han {total} nga lakang human na"],
  ["storage.litres", "{have} of {target} L", "{have} sa {target} L", "{have} han {target} L"],
  ["storage.alerts_title", "Alerts are on", "Naka-on ang alerto", "Naka-on an alerto"],
  ["storage.alerts_body", "You'll hear from us by app and SMS", "Makakatanggap ka ng balita sa app at SMS", "Makakarawat ka hin balita ha app ngan SMS"],
  ["storage.container", "Container {n}", "Lalagyan {n}", "Butangan {n}"],
  ["storage.container_litres", "{litres} L", "{litres} L", "{litres} L"],
  ["storage.container_full", "Container {n}, full", "Lalagyan {n}, puno na", "Butangan {n}, puno na"],
  ["storage.hint", "Tap a container when it's full. Fill now, while there's still pressure in the line.", "Pindutin ang lalagyan kapag puno na. Mag-ipon na habang malakas pa ang tulo.", "Pinduta an butangan kun puno na. Pag-ipon na samtang makusog pa an tubig ha tubo."],
  ["storage.done", "That's enough for 24 hours. No need to store more.", "Sapat na iyan para sa 24 oras. Hindi na kailangang mag-ipon pa.", "Igo na iton para ha 24 oras. Diri na kinahanglan mag-ipon pa."],

  // Backup sources
  ["runout.title", "If you run out", "Kung maubusan ka", "Kun maubusan ka"],
  ["runout.nearest", "Plan {letter} · nearest", "Plan {letter} · pinakamalapit", "Plan {letter} · pinakahirani"],
  ["runout.see_all", "See all {n} backup sources", "Tingnan ang {n} na reserbang mapagkukunan", "Kitaa an {n} nga reserba nga kuhaan"],
  ["source.safe", "Safe to drink", "Ligtas inumin", "Luwas imnon"],
  ["source.boil", "Boil before drinking", "Pakuluan bago inumin", "Pabukala antes imnon"],
  ["source.washing", "Washing only", "Panghugas lang", "Panhugas la"],
  ["source.walk", "{n} min walk", "{n} minutong lakad", "{n} minuto nga lakat"],
  ["source.free", "Free", "Libre", "Libre"],
  ["source.cost", "₱{price} per {litres} L", "₱{price} bawat {litres} L", "₱{price} kada {litres} L"],
  ["source.checked_by", "Checked by {name}, barangay water captain · {time}", "Sinuri ni {name}, barangay water captain · {time}", "Gin-check ni {name}, barangay water captain · {time}"],
  ["source.reported", "{name} · {time}", "{name} · {time}", "{name} · {time}"],
  ["source.live.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["source.live.open_stock", "Open · has stock", "Bukas · may stock", "Bukas · may stock"],
  ["source.live.queue", "Flowing · queue of ~{n}", "Dumadaloy · pila ng ~{n}", "Nagawas · linya nga ~{n}"],
  ["source.live.scheduled", "Scheduled {time}", "Nakaiskedyul {time}", "Naka-iskedyul {time}"],
  ["source.live.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["source.live.dry", "Dry", "Tuyo", "Hubas"],
  ["source.bring", "Bring containers", "Magdala ng lalagyan", "Pagdara hin butangan"],
  ["sources.title", "Your backup water plan", "Ang iyong reserbang plano sa tubig", "An imo reserba nga plano ha tubig"],
  ["sources.sub", "{barangay}. Ranked by safety first, then walking time, then cost.", "{barangay}. Inayos ayon sa kaligtasan, saka layo ng lakad, saka presyo.", "{barangay}. Ginhan-ay sumala han kaluwasan, katapos kahirayo han lakat, katapos presyo."],
  ["sources.legend_a", "Bars show the full round trip, queue included. The mark is ", "Ipinapakita ng guhit ang buong balikan, kasama ang pila. Ang marka ay ", "Ginpapakita han linya an bug-os nga balikan, upod an linya. An marka amo an "],
  ["sources.legend_b", "{min} minutes", "{min} minuto", "{min} minuto"],
  ["sources.legend_c", ", the WHO/UNICEF line for basic access.", ", ang pamantayan ng WHO/UNICEF para sa batayang access.", ", an sukol han WHO/UNICEF para ha basic nga access."],
  ["sources.plan_label", "Plan {letter}:", "Plan {letter}:", "Plan {letter}:"],
  ["sources.round_trip", "Round trip ≈ {n} min", "Balikan ≈ {n} min", "Balikan ≈ {n} min"],
  ["sources.over_line", "Round trip ≈ {n} min, over the {jmp}-min line", "Balikan ≈ {n} min, lampas sa {jmp}-min na guhit", "Balikan ≈ {n} min, labaw ha {jmp}-min nga linya"],

  // History tab (no wireframe yet)
  ["history.title", "History", "Kasaysayan", "Kasaysayan"],
  ["history.empty", "Past interruptions in your barangay will show here.", "Dito makikita ang mga nakaraang pagkawala ng tubig sa barangay mo.", "Dinhi makikita an mga naglabay nga pagkawara han tubig ha imo barangay."],

  // Barangay + language picker
  ["settings.title", "Your barangay", "Ang iyong barangay", "An imo barangay"],
  ["settings.sub", "We'll remember it on this phone.", "Tatandaan namin ito sa phone na ito.", "Hinunumdoman namon ini hini nga phone."],
  ["settings.language", "Language", "Wika", "Yinaknan"],
  ["settings.save", "Save", "I-save", "I-save"],
  ["lang.waray", "Waray", "Waray", "Waray"],
  ["lang.filipino", "Filipino", "Filipino", "Filipino"],
  ["lang.english", "English", "English", "English"],

  // Barangay water captain
  ["captain.role", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}"],
  ["captain.greeting_morning", "Good morning, {name}", "Magandang umaga, {name}", "Maupay nga aga, {name}"],
  ["captain.greeting_afternoon", "Good afternoon, {name}", "Magandang hapon, {name}", "Maupay nga kulop, {name}"],
  ["captain.greeting_evening", "Good evening, {name}", "Magandang gabi, {name}", "Maupay nga gab-i, {name}"],
  ["captain.up_to_date", "Up to date · {time}", "Updated · {time}", "Updated · {time}"],
  ["captain.works_offline", "Keeps working without signal", "Gumagana kahit walang signal", "Nagana bisan waray signal"],
  ["captain.piped_off", "Piped water is off", "Patay ang tubig sa tubo", "Patay an tubig ha tubo"],
  ["captain.piped_on", "Piped water is on", "May tubig sa tubo", "May tubig ha tubo"],
  ["captain.since", "Since {time} · {cause}", "Mula {time} · {cause}", "Tikang {time} · {cause}"],
  ["captain.expected_back", "Expected back", "Inaasahang babalik", "Ginlalaoman nga mabalik"],
  ["captain.relies_on", "Your barangay relies on", "Umaasa ang barangay mo sa", "Nasandig an imo barangay ha"],
  ["captain.n_sources", "{n} sources", "{n} mapagkukunan", "{n} nga kuhaan"],
  ["captain.round_title", "Morning round", "Pag-ikot sa umaga", "Paglibot ha aga"],
  ["captain.round_progress", "{done} of {total} checked", "{done} sa {total} nasuri", "{done} han {total} na-check"],
  ["captain.checked_at", "Checked {time}", "Nasuri {time}", "Na-check {time}"],
  ["captain.not_checked", "Not checked", "Hindi pa nasusuri", "Diri pa na-check"],
  ["captain.plan_line", "Plan {letter} · {safety}", "Plan {letter} · {safety}", "Plan {letter} · {safety}"],
  ["captain.toast", "Sent to {n} households", "Naipadala sa {n} na pamilya", "Ginpadara ha {n} nga pamilya"],
  ["captain.updates_title", "Your updates today", "Ang iyong mga update ngayon", "An imo mga update yana"],
  ["captain.delivered", "updates delivered", "update na naihatid", "update nga naihatod"],
  ["captain.to_working", "went to a working source", "pumunta sa gumaganang mapagkukunan", "kinadto ha nagana nga kuhaan"],
  ["captain.more_thanks", "+ {n} more thank-yous", "+ {n} pang pasasalamat", "+ {n} pa nga salamat"],
  ["seg.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["seg.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["seg.dry", "Dry", "Tuyo", "Hubas"],

  // CWD operator dashboard
  ["operator.org", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant"],
  ["operator.tab_monitor", "Monitor", "Monitor", "Monitor"],
  ["operator.tab_log", "Readings log", "Talaan ng readings", "Listahan han readings"],
  ["operator.tab_events", "Events", "Mga pangyayari", "Mga hitabo"],
  ["operator.tab_thresholds", "Thresholds", "Mga hangganan", "Mga utlan"],
  ["operator.shift", "Shift: {name} · {hours}", "Shift: {name} · {hours}", "Shift: {name} · {hours}"],
  ["operator.title", "Antiao intake · {day} {time}", "Antiao intake · {day} {time}", "Antiao intake · {day} {time}"],
  ["operator.event_open", "Event {id} open", "Bukas ang event {id}", "Bukas an event {id}"],
  ["operator.readings_pill", "Plant readings", "Readings ng planta", "Readings han planta"],
  ["operator.readings_sub", "Logged by you, hourly", "Ikaw ang nagtatala, kada oras", "Ikaw an nagsusurat, kada oras"],
  ["operator.readings_due", "Last {last} · {due} due", "Huli {last} · {due} ang susunod", "Katapusan {last} · {due} an sunod"],
  ["operator.rain_pill", "Rainfall over the catchment", "Ulan sa catchment", "Uran ha catchment"],
  ["operator.rain_sub", "Open-Meteo, automatic", "Open-Meteo, awtomatiko", "Open-Meteo, awtomatiko"],
  ["operator.raw", "Raw turbidity", "Raw turbidity", "Raw turbidity"],
  ["operator.over_limit", "Over limit", "Lampas sa limit", "Labaw ha limit"],
  ["operator.raw_over", "Above the {limit} plant limit since {time}", "Lampas sa {limit} na limit ng planta mula {time}", "Labaw ha {limit} nga limit han planta tikang {time}"],
  ["operator.raw_under", "Under the {limit} plant limit", "Mas mababa sa {limit} na limit ng planta", "Ubos han {limit} nga limit han planta"],
  ["operator.treated", "Treated turbidity", "Treated turbidity", "Treated turbidity"],
  ["operator.treated_under", "Under the {limit} NTU limit", "Mas mababa sa {limit} NTU na limit", "Ubos han {limit} NTU nga limit"],
  ["operator.treated_over", "Over the {limit} NTU limit", "Lampas sa {limit} NTU na limit", "Labaw ha {limit} NTU nga limit"],
  ["operator.clarifier", "Clarifier flow", "Daloy ng clarifier", "Agos han clarifier"],
  ["operator.clarifier_cut", "Capacity ≈ {cap} L/s · cut back", "Kapasidad ≈ {cap} L/s · binawasan", "Kapasidad ≈ {cap} L/s · ginkunhuran"],
  ["operator.clarifier_full", "Capacity ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s"],
  ["operator.reservoir", "Reservoir", "Reservoir", "Reservoir"],
  ["operator.reservoir_trend", "Falling ~{n} points an hour", "Bumababa ~{n} puntos kada oras", "Nauubos ~{n} puntos kada oras"],
  ["unit.ntu", "NTU", "NTU", "NTU"],
  ["unit.lps", "L/s", "L/s", "L/s"],
  ["unit.pct", "%", "%", "%"],
  ["operator.chart_turbidity", "Raw turbidity, last 24 hours", "Raw turbidity, nakaraang 24 oras", "Raw turbidity, naglabay nga 24 oras"],
  ["operator.chart_units", "NTU · hourly", "NTU · kada oras", "NTU · kada oras"],
  ["operator.plant_limit", "Plant limit {limit} NTU", "Limit ng planta {limit} NTU", "Limit han planta {limit} NTU"],
  ["operator.now_value", "{value} now", "{value} ngayon", "{value} yana"],
  ["operator.chart_rain", "Rainfall over the Antiao catchment", "Ulan sa Antiao catchment", "Uran ha Antiao catchment"],
  ["operator.rain_summary", "mm per hour · {mm} mm since {time} · {days} dry-spell days", "mm kada oras · {mm} mm mula {time} · {days} araw na tagtuyot", "mm kada oras · {mm} mm tikang {time} · {days} ka adlaw nga hulaw"],
  ["operator.log_title", "Log the {time} reading", "Itala ang reading ng {time}", "Isurat an reading han {time}"],
  ["operator.last_logged", "Last logged {time} by you", "Huling naitala {time} mo", "Katapusan nga ginsurat {time} nimo"],
  ["operator.field_raw", "Raw turbidity (NTU)", "Raw turbidity (NTU)", "Raw turbidity (NTU)"],
  ["operator.field_treated", "Treated turbidity (NTU)", "Treated turbidity (NTU)", "Treated turbidity (NTU)"],
  ["operator.field_clarifier", "Clarifier flow (L/s)", "Daloy ng clarifier (L/s)", "Agos han clarifier (L/s)"],
  ["operator.field_reservoir", "Reservoir (%)", "Reservoir (%)", "Reservoir (%)"],
  ["operator.field_status", "Plant status", "Kalagayan ng planta", "Kahimtang han planta"],
  ["plant.normal", "Normal", "Normal", "Normal"],
  ["plant.degraded", "Reduced output", "Bawas na output", "Gin-kunhuran nga output"],
  ["plant.shutdown", "Shut down", "Nakasara", "Sirado"],
  ["operator.save", "Save reading", "I-save ang reading", "I-save an reading"],
  ["operator.save_hint", "Saves offline if the plant connection drops.", "Nase-save offline kapag nawala ang koneksyon ng planta.", "Nase-save offline kun mawara an koneksyon han planta."],
  ["operator.saved", "Saved on this device. {n} waiting to send.", "Naka-save sa device na ito. {n} naghihintay maipadala.", "Naka-save hini nga device. {n} naghuhulat ipadara."],
  ["operator.invalid", "Check the highlighted numbers.", "Suriin ang mga numerong naka-highlight.", "I-check an mga numero nga naka-highlight."],
  ["operator.err_number", "Enter a number, 0 or more", "Maglagay ng numero, 0 pataas", "Pagbutang hin numero, 0 pataas"],
  ["operator.err_pct", "Enter a number from 0 to 100", "Maglagay ng numero mula 0 hanggang 100", "Pagbutang hin numero tikang 0 tubtob 100"],
  ["detector.label", "Disruption detector", "Disruption detector", "Disruption detector"],
  ["detector.turbidity", "Turbidity spike", "Biglang paglabo", "Kalit nga paglubog"],
  ["detector.matched", "{n} of {total} signals match. You confirmed it at {time}.", "{n} sa {total} senyales ang tugma. Kinumpirma mo ito noong {time}.", "{n} han {total} nga senyales an tugma. Gin-kumpirma mo ini han {time}."],
  ["detector.sig_raw", "Raw turbidity above {limit} NTU since {time}", "Raw turbidity lampas {limit} NTU mula {time}", "Raw turbidity labaw {limit} NTU tikang {time}"],
  ["detector.sig_rain", "{mm} mm of rain in {hours} hours over the catchment", "{mm} mm na ulan sa loob ng {hours} oras sa catchment", "{mm} mm nga uran ha sulod han {hours} oras ha catchment"],
  ["detector.sig_clarifier", "Clarifier cut from {from} to {to} L/s", "Clarifier binawasan mula {from} hanggang {to} L/s", "Clarifier ginkunhuran tikang {from} ngadto {to} L/s"],
  ["detector.low_source", "Low source level", "Mababang lebel ng pinagkukunan", "Ubos nga lebel han kuhaan"],
  ["detector.low_source_note", "{n} of {total} · no dry spell, intake normal", "{n} sa {total} · walang tagtuyot, normal ang intake", "{n} han {total} · waray hulaw, normal an intake"],
  ["detector.repair", "Repair work", "Pag-aayos", "Pag-ayad"],
  ["detector.repair_note", "{n} of {total} · nothing scheduled", "{n} sa {total} · walang nakaiskedyul", "{n} han {total} · waray naka-iskedyul"],
  ["detector.window", "Time window residents see", "Oras na nakikita ng mga residente", "Oras nga nakikita han mga residente"],
  ["detector.window_value", "{window} · likely {likely}", "{window} · malamang {likely}", "{window} · posible {likely}"],
  ["detector.adjust", "Adjust", "Baguhin", "Igbag-o"],
  ["detector.next", "Next resident update due {time}. You'll be reminded at {remind}.", "Susunod na update sa residente bago mag-{time}. Ipapaalala sa iyo sa {remind}.", "Sunod nga update ha residente antes han {time}. Pahinumdoman ka ha {remind}."],
  ["warnings.title", "Your early warnings", "Ang iyong maagang babala", "An imo temprano nga pahimangno"],
  ["warnings.sub", "How much notice your flags gave residents before taps ran dry", "Gaano kaaga nabalitaan ng mga residente bago naubos ang tubig", "Pira ka temprano nabaltakan an mga residente antes nahubsan an gripo"],
  ["warnings.turbidity", "turbidity", "labo", "lubog"],
  ["warnings.repair", "pipe repair", "ayos ng tubo", "pag-ayad han tubo"],
  ["warnings.low_source", "low source", "mababang pinagkukunan", "ubos nga kuhaan"],
  ["warnings.note", "All three confirmed by the LGU after the event closed.", "Kinumpirma ng LGU ang tatlo matapos ang event.", "Gin-kumpirma han LGU an tulo katapos han event."],
  ["operator.footnote", "Thresholds from the CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Confirm they are current before launch. Readings shown are sample data.", "Mga hangganan mula sa CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Kumpirmahin bago ilunsad. Sample data ang mga reading.", "Mga utlan tikang ha CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Kumpirmaha antes ilunsad. Sample data an mga reading."],

  // Admin placeholder (spec 07)
  ["admin.org", "Catbalogan CDRRMO", "Catbalogan CDRRMO", "Catbalogan CDRRMO"],
  ["admin.placeholder_title", "LGU dashboard", "LGU dashboard", "LGU dashboard"],
  ["admin.placeholder_body", "The live dashboard comes next, in spec 07.", "Susunod ang live dashboard, sa spec 07.", "Sunod an live dashboard, ha spec 07."],

  // LGU allocation (spec 06, wireframe p.10)
  ["lgu.tab_priorities", "Set priorities", "Itakda ang prayoridad", "Igbutang an prayoridad"],
  ["lgu.tab_records", "Event records", "Talaan ng mga event", "Listahan han mga event"],
  ["lgu.event_pill", "Event {id} · {cause}", "Event {id} · {cause}", "Event {id} · {cause}"],
  ["lgu.cause.turbidity", "turbidity spike", "biglang paglabo", "kalit nga paglubog"],
  ["lgu.cause.drought", "low river", "mababang ilog", "hubas nga salog"],
  ["lgu.cause.repair", "pipe repair", "pag-aayos ng tubo", "pag-ayad han tubo"],
  ["lgu.officer_line", "{time} · {name}, CDRRMO", "{time} · {name}, CDRRMO", "{time} · {name}, CDRRMO"],
  ["lgu.title", "Who gets water first?", "Sino ang unang bibigyan ng tubig?", "Hin-o an siyahan nga hatagan hin tubig?"],
  ["lgu.what_happened", "What happened", "Ano ang nangyari", "Ano an nahitabo"],
  ["lgu.headline.turbidity", "River too muddy to treat", "Sobrang labo ng ilog para linisin", "Sobra kalubog an salog para limpyohan"],
  ["lgu.headline.drought", "River too low to supply everyone", "Masyadong mababa ang ilog para sa lahat", "Sobra kahubas an salog para ha ngatanan"],
  ["lgu.headline.repair", "Pipes under repair", "Inaayos ang mga tubo", "Ginaayad an mga tubo"],
  ["lgu.flagged_by", "Flagged by {who} at {time}", "Itinala ng {who} noong {time}", "Ginmarkahan han {who} han {time}"],
  ["lgu.who_affected", "Who's affected", "Sino ang apektado", "Hin-o an apektado"],
  ["lgu.households", "{n} households", "{n} pamilya", "{n} nga pamilya"],
  ["lgu.affected_sub", "{barangays} barangays · {no_backup} with no backup nearby", "{barangays} barangay · {no_backup} walang malapit na reserba", "{barangays} nga barangay · {no_backup} waray hirani nga reserba"],
  ["lgu.expected_back", "Expected back", "Inaasahang babalik", "Ginlalaoman nga mabalik"],
  ["lgu.window_today", "{window} today", "{window} ngayong araw", "{window} yana nga adlaw"],
  ["lgu.most_likely", "Most likely around {time}", "Malamang bandang {time}", "Posible mga {time}"],
  ["lgu.decision_step", "Your decision · step {n} of {total}", "Ang iyong desisyon · hakbang {n} sa {total}", "An imo desisyon · lakang {n} han {total}"],
  ["lgu.decision_title", "Check the order below", "Suriin ang pagkakasunod sa ibaba", "Kitaa an han-ay ha ubos"],
  ["lgu.decision_body", "Then confirm to notify residents and route trucks", "Saka kumpirmahin para abisuhan ang residente at ipadala ang trak", "Katapos kumpirmaha para pahibaruon an residente ngan ipadara an trak"],
  ["lgu.decision_done_title", "Order confirmed", "Nakumpirma ang pagkakasunod", "Nakumpirma an han-ay"],
  ["lgu.decision_done_body", "Waiting for the server to notify residents", "Hinihintay ang server para abisuhan ang residente", "Ginhuhulat an server para pahibaruon an residente"],
  ["lgu.priority_title", "Priority order", "Pagkakasunod ng prayoridad", "Han-ay han prayoridad"],
  ["lgu.priority_rule", "Ranked by need, then by access to a backup within {jmp} min", "Inayos ayon sa pangangailangan, saka sa reserbang abot sa loob ng {jmp} min", "Ginhan-ay sumala han kinahanglan, katapos han reserba nga maabot ha sulod han {jmp} min"],
  ["facility.health_station", "Health station", "Health station", "Health station"],
  ["facility.school", "School", "Paaralan", "Eskwelahan"],
  ["facility.evacuation_center", "Evacuation center", "Evacuation center", "Evacuation center"],
  ["lgu.need.vulnerable", "{n} elderly or PWD", "{n} matanda o PWD", "{n} gurang o PWD"],
  ["lgu.need.no_backup", "{n} off-network, no backup within {jmp} min", "{n} wala sa tubo, walang reserba sa loob ng {jmp} min", "{n} waray ha tubo, waray reserba ha sulod han {jmp} min"],
  ["lgu.need.covered", "At least one safe backup within {jmp} min", "May ligtas na reserba sa loob ng {jmp} min", "May luwas nga reserba ha sulod han {jmp} min"],
  ["lgu.estimate", "estimate", "tantiya", "banabana"],
  ["lgu.coverage_unknown", "coverage unknown", "hindi alam ang sakop", "diri maaram an sakop"],
  ["lgu.reported_not_restored", "Reported not restored", "Iniulat na wala pang tubig", "Ginreport nga waray pa tubig"],
  ["lgu.moved_from", "Moved from #{from}", "Inilipat mula #{from}", "Ginbalhin tikang #{from}"],
  ["lgu.move_up", "Move {name} up", "Itaas ang {name}", "Igtaas an {name}"],
  ["lgu.move_down", "Move {name} down", "Ibaba ang {name}", "Igpaubos an {name}"],
  ["lgu.affected_title", "Affected", "Apektado", "Apektado"],
  ["lgu.stat_barangays", "Barangays", "Barangay", "Barangay"],
  ["lgu.stat_households", "Households", "Pamilya", "Pamilya"],
  ["lgu.stat_off_network", "Off the piped network, no backup within {jmp} min", "Wala sa tubo, walang reserba sa loob ng {jmp} min", "Waray ha tubo, waray reserba ha sulod han {jmp} min"],
  ["lgu.stat_vulnerable", "Bedridden, elderly or PWD flagged", "May markang bedridden, matanda o PWD", "May marka nga bedridden, gurang o PWD"],
  ["lgu.stat_facilities", "Facilities", "Pasilidad", "Pasilidad"],
  ["lgu.facilities_value", "{health} health stations · {school} schools · {evac} evacuation centers", "{health} health station · {school} paaralan · {evac} evacuation center", "{health} health station · {school} eskwelahan · {evac} evacuation center"],
  ["lgu.route_title", "Water you can route", "Tubig na maipapadala", "Tubig nga maipapadara"],
  ["lgu.trucks", "LGU trucks", "Trak ng LGU", "Trak han LGU"],
  ["lgu.trucks_value", "{trucks} trucks · {trips} trips each", "{trucks} trak · {trips} biyahe bawat isa", "{trucks} nga trak · {trips} nga biyahe kada usa"],
  ["lgu.truck_water", "Truck water before {time}", "Tubig ng trak bago mag-{time}", "Tubig han trak antes han {time}"],
  ["lgu.litres_approx", "≈ {litres} L", "≈ {litres} L", "≈ {litres} L"],
  ["lgu.partners", "Station partners open", "Bukas na station partner", "Bukas nga station partner"],
  ["lgu.partners_value", "{open} of {total}", "{open} sa {total}", "{open} han {total}"],
  ["lgu.confirm_title", "Confirm and notify", "Kumpirmahin at abisuhan", "Kumpirmaha ngan pahibaruon"],
  ["lgu.confirm_body", "Residents get the status, the time window and their backup plan. Trucks are routed in this order. You can change the plan later; each version is logged.", "Makukuha ng residente ang status, oras, at reserbang plano. Ipapadala ang trak ayon sa ayos na ito. Mababago mo ito mamaya; naitatala ang bawat bersyon.", "Makakarawat an residente han kahimtang, oras, ngan reserba nga plano. Ipapadara an trak sumala hini nga han-ay. Mababag-o mo ini huhuraaw; ginsusurat an kada bersyon."],
  ["lgu.confirm_button", "Confirm priorities as {name}", "Kumpirmahin bilang {name}", "Kumpirmaha sugad nga {name}"],
  ["lgu.changes_none", "Recommended order, no changes.", "Inirekomendang ayos, walang pagbabago.", "Girekomenda nga han-ay, waray pagbag-o."],
  ["lgu.changes_some", "{n} changed from the recommended order.", "{n} ang binago mula sa inirekomendang ayos.", "{n} an ginbag-o tikang ha girekomenda nga han-ay."],
  ["lgu.log_note", "Every change is saved to the allocation log under your name, with the time.", "Bawat pagbabago ay naitatala sa allocation log sa ilalim ng pangalan mo, kasama ang oras.", "An kada pagbag-o ginsusurat ha allocation log ilarom han imo ngaran, upod an oras."],
  ["lgu.saving", "Saving…", "Sine-save…", "Gin-sesave…"],
  ["lgu.not_connected", "Not sent yet. The server that saves this and notifies residents isn't connected, so nothing has left this screen.", "Hindi pa naipadala. Hindi pa konektado ang server na nagse-save at nag-aabiso, kaya walang lumabas sa screen na ito.", "Diri pa naipadara. Diri pa konektado an server nga nagse-save ngan nagpapahibaro, salit waray gumawas hini nga screen."],

  // Event record (spec 06 AC5 + MEM-1, wireframe p.11)
  ["record.download", "Download record", "I-download ang talaan", "I-download an listahan"],
  ["record.closed", "Closed · water restored {time}", "Sarado · bumalik ang tubig {time}", "Sirado · nabalik an tubig {time}"],
  ["record.title", "{id} · {cause}", "{id} · {cause}", "{id} · {cause}"],
  ["record.cause.turbidity", "Turbidity spike", "Biglang paglabo", "Kalit nga paglubog"],
  ["record.cause.drought", "Low river", "Mababang ilog", "Hubas nga salog"],
  ["record.cause.repair", "Pipe repair", "Pag-aayos ng tubo", "Pag-ayad han tubo"],
  ["record.subtitle", "{day} · {start} to {end} · saved automatically when supply returned", "{day} · {start} hanggang {end} · awtomatikong na-save nang bumalik ang tubig", "{day} · {start} tubtob {end} · awtomatiko nga na-save han nabalik an tubig"],
  ["record.hero", "Residents heard from you {diff} sooner than in {month}.", "Mas maaga ng {diff} nakatanggap ng balita ang residente kaysa noong {month}.", "Mas temprano hin {diff} nakarawat hin balita an residente kaysa han {month}."],
  ["record.hero_body", "And the {n} off-network households were on the map this time. In the {month} event they weren't tracked at all.", "At nasa mapa na ngayon ang {n} pamilyang wala sa tubo. Noong {month}, hindi sila nasubaybayan.", "Ngan aada na ha mapa yana an {n} nga pamilya nga waray ha tubo. Han {month}, diri hira nasubay."],
  ["record.notice_label", "Notice to residents after CWD flag", "Abiso sa residente matapos ang marka ng CWD", "Pahibaro ha residente katapos han marka han CWD"],
  ["record.notice_prev", "{month} event: {value}", "Event noong {month}: {value}", "Event han {month}: {value}"],
  ["record.stat_duration", "Duration", "Tagal", "Kadugayon"],
  ["record.stat_barangays", "Barangays", "Barangay", "Barangay"],
  ["record.stat_households", "Households", "Pamilya", "Pamilya"],
  ["record.stat_truck", "Truck water delivered", "Naihatid na tubig ng trak", "Naihatod nga tubig han trak"],
  ["record.stat_vs", "Restored vs likely time", "Pagbalik kumpara sa inaasahan", "Pagbalik kumpara ha ginlaoman"],
  ["record.early", "{n} min early", "{n} min mas maaga", "{n} min mas temprano"],
  ["record.late", "{n} min late", "{n} min huli", "{n} min ulahi"],
  ["record.litres", "{litres} L", "{litres} L", "{litres} L"],
  ["record.what_happened", "What happened", "Ano ang nangyari", "Ano an nahitabo"],
  ["event.predicted", "Raw turbidity passed {limit} NTU", "Lumampas sa {limit} NTU ang raw turbidity", "Linmapos ha {limit} NTU an raw turbidity"],
  ["event.confirmed", "CWD confirmed a turbidity spike · {actor}", "Kinumpirma ng CWD ang paglabo · {actor}", "Gin-kumpirma han CWD an paglubog · {actor}"],
  ["event.deployed_priorities", "Priorities confirmed · {actor}", "Nakumpirma ang prayoridad · {actor}", "Nakumpirma an prayoridad · {actor}"],
  ["event.notified", "{n} households notified by app and SMS", "{n} pamilya ang naabisuhan sa app at SMS", "{n} nga pamilya an napahibaro ha app ngan SMS"],
  ["event.deployed_truck", "Truck water at {place}", "Tubig ng trak sa {place}", "Tubig han trak ha {place}"],
  ["event.resident_confirmed", "{n} residents confirmed water is back", "{n} residente ang nagkumpirmang bumalik ang tubig", "{n} nga residente an nag-kumpirma nga nabalik an tubig"],
  ["event.resolved", "Water restored · residents notified", "Bumalik ang tubig · naabisuhan ang residente", "Nabalik an tubig · napahibaro an residente"],
  ["record.alloc_title", "Allocation log", "Allocation log", "Allocation log"],
  ["record.alloc_sub", "Every decision, who made it, and when", "Bawat desisyon, sino ang gumawa, at kailan", "Kada desisyon, hin-o an naghimo, ngan san-o"],
  ["record.col_time", "Time", "Oras", "Oras"],
  ["record.col_decision", "Decision", "Desisyon", "Desisyon"],
  ["record.col_by", "By", "Ni", "Ni"],
  ["alloc.generated", "Recommended order generated from need and {jmp}-minute access", "Nabuo ang inirekomendang ayos mula sa pangangailangan at {jmp}-minutong access", "Nahimo an girekomenda nga han-ay tikang ha kinahanglan ngan {jmp}-minuto nga access"],
  ["alloc.confirmed", "Recommended order confirmed; trucks routed to {first} first", "Nakumpirma ang ayos; unang pinadalhan ng trak ang {first}", "Nakumpirma an han-ay; siyahan nga ginpadad-an hin trak an {first}"],
  ["alloc.moved", "{name} moved from #{from} to #{to}: {reason}", "Inilipat ang {name} mula #{from} sa #{to}: {reason}", "Ginbalhin an {name} tikang #{from} ngadto #{to}: {reason}"],
  ["alloc.closed", "Event closed; trucks released", "Sarado ang event; pinauwi ang trak", "Sirado an event; ginpauli an trak"],
  ["alloc.system", "System", "System", "System"],
  ["record.hours_title", "Hours without piped water in {year}", "Oras na walang tubig sa tubo noong {year}", "Oras nga waray tubig ha tubo han {year}"],
  ["record.hours_sub", "Affected barangays, all causes", "Apektadong barangay, lahat ng sanhi", "Apektado nga barangay, ngatanan nga hinungdan"],
  ["record.carry_title", "Carry this into the next event", "Dalhin ito sa susunod na event", "Darha ini ha sunod nga event"],
  ["record.carry_body", "Turbidity passed the plant limit about an hour after catchment rain reached {mm} mm. Next time, pre-alert {places} the moment rain reaches {mm} mm, before the plant has to cut back.", "Lumampas sa limit ang turbidity mga isang oras matapos umabot sa {mm} mm ang ulan. Sa susunod, abisuhan agad ang {places} pag umabot sa {mm} mm ang ulan, bago magbawas ang planta.", "Linmapos ha limit an turbidity mga usa ka oras katapos umabot ha {mm} mm an uran. Ha sunod, pahibaroa dayon an {places} kun umabot ha {mm} mm an uran, antes magkunhod an planta."],
  ["record.add_rule", "Add as an early-warning rule", "Idagdag bilang maagang babala", "Idugang sugad nga temprano nga pahimangno"],
  ["record.not_now", "Not now", "Hindi muna", "Diri anay"],
  ["record.sample", "Sample data throughout.", "Sample data ang lahat.", "Sample data an ngatanan."],

  // Resident / captain confirmation (spec 06 AC3–AC4)
  ["confirm.title_resident", "Is water back at your tap?", "Bumalik na ba ang tubig sa gripo mo?", "Nabalik na ba an tubig ha imo gripo?"],
  ["confirm.title_captain", "Is water back in {barangay}?", "Bumalik na ba ang tubig sa {barangay}?", "Nabalik na ba an tubig ha {barangay}?"],
  ["confirm.yes", "Yes, it's back", "Oo, bumalik na", "Oo, nabalik na"],
  ["confirm.no", "Still no water", "Wala pa ring tubig", "Waray pa gihapon tubig"],
  ["confirm.saved_yes", "Thanks. Saved on this phone; it goes to the LGU when there's signal.", "Salamat. Naka-save sa phone; ipapadala sa LGU pag may signal.", "Salamat. Naka-save ha phone; ipapadara ha LGU kun may signal."],
  ["confirm.saved_no", "Saved on this phone. Once it's sent, the LGU puts your barangay back on the priority list.", "Naka-save sa phone. Kapag naipadala, ibabalik ng LGU ang barangay mo sa listahan.", "Naka-save ha phone. Kun naipadara na, ibabalik han LGU an imo barangay ha listahan."],

  // Water's back (spec 06 resolved state, wireframe p.6)
  ["back.time", "Back at {time}", "Bumalik {time}", "Nabalik {time}"],
  ["back.earlier", "{n} minutes earlier", "{n} minutong mas maaga", "{n} minuto nga mas temprano"],
  ["back.later", "{n} minutes later", "{n} minutong mas huli", "{n} minuto nga mas ulahi"],
  ["back.vs_rest", " than our best estimate of {time}. Off for {duration}.", " kaysa sa tantiya naming {time}. Nawala nang {duration}.", " kaysa han amon banabana nga {time}. Nawara hin {duration}."],
  ["back.headline", "Water's back.", "Bumalik na ang tubig.", "Nabalik na an tubig."],
  ["back.sub", "You were ready all day.", "Handa ka buong araw.", "Andam ka bug-os nga adlaw."],
  ["back.tip_run", "Let the tap run until the water is clear before drinking.", "Padaluyin muna ang gripo hanggang luminaw bago inumin.", "Pabay-i anay nga magawas an gripo tubtob tumin-aw antes imnon."],
  ["back.tip_keep", "Keep your {litres} L for one more day, then use it for washing.", "Itabi ang {litres} L ng isa pang araw, saka gamitin panghugas.", "Tipigi an {litres} L hin usa pa ka adlaw, katapos gamita panhugas."],
  ["back.captain", "{name} checked your sources {n} times today.", "{n} beses sinuri ni {name} ang mga mapagkukunan ngayon.", "{n} ka beses gin-check ni {name} an mga kuhaan yana."],
  ["back.captain_reach", "{name}'s updates sent {n} households in {barangay} to working water.", "Dahil sa update ni {name}, {n} pamilya sa {barangay} ang nakakuha ng tubig.", "Tungod han update ni {name}, {n} nga pamilya ha {barangay} an nakakuha hin tubig."],
  ["back.thanks", "Say thanks to {name}", "Magpasalamat kay {name}", "Pagpasalamat kan {name}"],
] as const;

export type CopyKeyName = (typeof ROWS)[number][0];

export const COPY: CopyKey[] = ROWS.map(([key, english, filipino, waray]) =>
  CopyKey.parse({ key, english, filipino, waray }),
);

export const COPY_BY_KEY = new Map(COPY.map((row) => [row.key, row]));

// Spec 08: strings the team isn't sure of. Today that's every Waray and Filipino draft.
export const NEEDS_REVIEW = { waray: "all", filipino: "all" } as const;
