// SPEC: 08 — the one trilingual CopyKey table. Every user-facing string lives here.
// Rows are [key, english, filipino, waray]. {placeholders} are filled by t().
//
// REVIEW: every Waray and Filipino string for resident/captain screens is a draft by the dev team,
// not a native-speaker review. Spec 08 says flag, don't guess: they're all listed in
// NEEDS_REVIEW below until a fluent teammate checks them. English is the default
// language until then. LGU screens (lgu.*, record.*, event.*, alloc.*) render English only (spec 08 Decisions).
import { CopyKey } from "../contracts/spec08";

const ROWS = [
  // App shell
  ["app.name", "PIA WaterBack", "PIA WaterBack", "PIA WaterBack"],
  ["app.offline_stale", "No signal · showing what was saved at {time}", "Walang signal · ipinapakita ang naka-save noong {time}", "Waray signal · ginpapakita an naka-save han {time}"],
  ["app.loading", "Getting the latest status…", "Kinukuha ang pinakabagong balita…", "Ginkukuha an pinakabag-o nga kahimtang…"],
  ["app.error_title", "We can't reach PIA WaterBack right now", "Hindi namin maabot ang PIA WaterBack ngayon", "Diri namon maabot an PIA WaterBack yana"],
  ["app.error_body", "Check your signal, then try again.", "Tingnan ang signal, saka subukan ulit.", "Kitaa an signal, katapos utroha."],
  ["app.retry", "Try again", "Subukan ulit", "Utroha"],
  ["app.updated_at", "Updated {time}", "Na-update {time}", "Gin-update {time}"],
  ["app.back", "Back", "Bumalik", "Balik"],
  ["notfound.title", "We can't find this page", "Hindi namin makita ang pahinang ito", "Diri namon makita ini nga pahina"],
  ["notfound.body", "The link may be old or typed wrong. Your water news is one tap away.", "Baka luma o mali ang pagkaka-type ng link. Isang pindot lang ang balita sa tubig.", "Bangin daan o sayop an pagkasurat han link. Usa la nga pindot an balita ha tubig."],
  ["notfound.home", "Check my water status", "Tingnan ang lagay ng tubig ko", "Kitaa an kahimtang han akon tubig"],
  ["notfound.sources", "Find backup water", "Maghanap ng reserbang tubig", "Pagbiling hin reserba nga tubig"],
  ["error.title", "Something went wrong on this page", "May nagkamali sa pahinang ito", "May sayop hini nga pahina"],
  ["error.body", "Try again. If it keeps happening, start from your water status.", "Subukan ulit. Kung mangyari ulit, magsimula sa lagay ng tubig mo.", "Utroha. Kun mahitabo utro, pagtikang ha kahimtang han imo tubig."],

  // Resident bottom bar
  ["nav.status", "Status", "Status", "Kahimtang"],
  ["nav.sources", "Sources", "Mapagkukunan", "Kuhaan"],
  ["nav.history", "History", "Kasaysayan", "Kasaysayan"],

  // Water states (signal level → state, see lib/waterState.ts)
  ["state.flowing.chip", "Flowing", "Dumadaloy", "Nagawas"],
  ["state.flowing.headline", "Water is flowing", "May tubig", "May tubig"],
  ["state.flowing.sub", "Next planned work: none", "Susunod na nakaplanong trabaho: wala", "Sunod nga plano nga trabaho: waray"],
  ["state.headsup.chip", "Heads-up", "Paalala", "Pahinumdom"],
  ["state.headsup.headline", "Store water tonight", "Mag-ipon ng tubig ngayong gabi", "Pag-ipon hin tubig yana nga gab-i"],
  ["state.headsup.sub", "Likely to stop from {time}", "Posibleng mawala simula {time}", "Posible mawara tikang {time}"],
  // Heads-up urgency (resident state v2: a prediction never says water is off). DRAFT FIL/WAR: native review (see NEEDS_REVIEW).
  ["state.headsup.possible.headline", "Water may stop. Keep some stored", "Maaaring mawalan ng tubig. Mag-ipon ng kaunti", "Basi mawara an tubig. Pag-ipon anay hin gutiay"],
  ["state.headsup.very_likely.headline", "Water likely to stop soon. Store water now", "Malamang na mawalan ng tubig. Mag-ipon na ngayon", "Posible gud nga mawara an tubig. Pag-ipon na yana"],
  ["state.headsup.very_likely.headline_at", "Water likely to stop from {time}. Store water now", "Malamang na mawalan ng tubig simula {time}. Mag-ipon na ngayon", "Posible gud nga mawara an tubig tikang {time}. Pag-ipon na yana"],
  // Heads-up card (resident/captain). A heads-up is a prediction: water is still ON. DRAFT FIL/WAR: native review.
  ["headsup.still_on", "Your water is still on. This is an early warning, not an outage.", "May tubig pa ngayon. Maagang babala ito, hindi pagkawala ng tubig.", "May tubig pa yana. Temprano nga pahimangno ini, diri pa nawara an tubig."],
  ["headsup.likely_at", "Most likely from {time}", "Pinakamalamang simula {time}", "Pinakaposible tikang {time}"],
  ["headsup.within_48h", "Could happen within the next 48 hours", "Maaaring mangyari sa loob ng 48 oras", "Mahimo mahitabo ha sulod hin 48 nga oras"],
  ["headsup.store", "Store {litres} L now ({people} people × {per} L each)", "Mag-ipon ng {litres} L ngayon ({people} tao × {per} L bawat isa)", "Pag-ipon hin {litres} L yana ({people} nga tawo × {per} L kada usa)"],
  ["headsup.why", "Why we think so: {reason}", "Bakit namin ito sinasabi: {reason}", "Kay ano nga amon ini ginsiring: {reason}"],
  ["headsup.see_sources", "See backup water sources", "Tingnan ang mga reserbang tubig", "Kitaa an mga reserba nga tubig"],
  ["headsup.vulnerable", "{n} vulnerable households on your list. Check on them first.", "{n} bulnerableng pamilya sa listahan mo. Silipin sila muna.", "{n} nga bulnerable nga pamilya ha imo listahan. Tan-awa anay hira."],
  ["state.interrupted.chip", "Interrupted", "Naputol", "Naputol"],
  ["state.interrupted.headline", "No water from the tap", "Walang tubig sa gripo", "Waray tubig ha gripo"],
  ["state.repair.chip", "Planned repair", "Nakaplanong ayos", "Plano nga pag-ayad"],
  ["state.repair.headline", "Off for a pipe repair", "Patay dahil sa pag-aayos ng tubo", "Patay kay ginaayad an tubo"],
  ["cause.turbidity", "The water is too turbid to treat.", "Sobrang labo ng tubig para linisin.", "Sobra kalubog an tubig para limpyohan."],
  ["cause.drought", "The river is too low to supply everyone.", "Masyadong mababa ang ilog para sa lahat.", "Sobra kahubas an salog para ha ngatanan."],
  ["cause.repair", "The pipes are being repaired.", "Inaayos ang mga tubo.", "Ginaayad an mga tubo."],
  ["cause_short.turbidity", "water too turbid to treat", "sobrang labo ng tubig", "sobra kalubog an tubig"],
  ["cause_short.drought", "river too low", "masyadong mababa ang ilog", "sobra kahubas an salog"],
  ["cause_short.repair", "pipe repair", "pag-aayos ng tubo", "pag-ayad han tubo"],

  // Resident status card
  ["status.back_between", "Water will be back today between", "Babalik ang tubig ngayong araw sa pagitan ng", "Mabalik an tubig yana nga adlaw butnga han"],
  ["status.back_between_tomorrow", "Water will be back tomorrow between", "Babalik ang tubig bukas sa pagitan ng", "Mabalik an tubig buwas butnga han"],
  ["status.back_between_on", "Water will be back on {day} between", "Babalik ang tubig sa {day} sa pagitan ng", "Mabalik an tubig ha {day} butnga han"],
  ["status.back_between_days", "Water will be back between", "Babalik ang tubig sa pagitan ng", "Mabalik an tubig butnga han"],
  ["status.day_today", "Today", "Ngayon", "Yana"],
  ["status.day_tomorrow", "Tomorrow", "Bukas", "Buwas"],
  ["status.chart_stopped", "Stopped", "Huminto", "Tumunong"],
  ["status.chart_back", "Water back", "Balik ang tubig", "Balik an tubig"],
  ["status.chart_sr", "Water stopped at {stopped}. It is now {now}. Water is expected back between {window}.", "Huminto ang tubig nang {stopped}. Ngayon ay {now}. Inaasahang babalik ang tubig sa pagitan ng {window}.", "Tumunong an tubig han {stopped}. Yana {now}. Ginlalaoman nga mabalik an tubig butnga han {window}."],
  ["status.now", "Now", "Ngayon", "Yana"],
  ["status.dry_minutes", "No water for {n} minutes", "Walang tubig sa loob ng {n} minuto", "Waray tubig ha sulod hin {n} nga minuto"],
  ["status.dry_hour", "No water for 1 hour", "Walang tubig sa loob ng 1 oras", "Waray tubig ha sulod hin 1 nga oras"],
  ["status.dry_hours", "No water for {n} hours", "Walang tubig sa loob ng {n} oras", "Waray tubig ha sulod hin {n} nga oras"],
  ["status.wait_late", "We expected water back by {time}. We're still checking.", "Inaasahan namin ang tubig bago mag-{time}. Tinitingnan pa namin.", "Gin-asya namon nga mabalik an tubig antes han {time}. Ginsusi pa namon."],
  ["status.next_update_by", "Next update by {time}", "Susunod na update bago mag-{time}", "Sunod nga update antes han {time}"],
  ["status.next_update_rest", ", even if nothing changes.", ", kahit walang pagbabago.", ", bisan waray pagbag-o."],
  ["action.store_water", "Store water", "Mag-ipon ng tubig", "Pag-ipon hin tubig"],
  ["action.find_water", "Find water", "Maghanap ng tubig", "Pangita hin tubig"],

  // Storage plan
  ["storage.title", "Store {litres} L for 24 hours", "Mag-ipon ng {litres} L para sa 24 oras", "Pag-ipon hin {litres} L para ha 24 oras"],
  ["storage.household", "For your household of {people} · {per} L per person", "Para sa pamilya ng {people} · {per} L bawat tao", "Para ha pamilya nga {people} · {per} L kada tawo"],
  ["storage.steps", "{done} of {total} steps done", "{done} sa {total} hakbang tapos na", "{done} han {total} nga lakang human na"],
  ["storage.litres", "{have} of {target} L", "{have} sa {target} L", "{have} han {target} L"],
  ["storage.container", "Container {n}", "Lalagyan {n}", "Butangan {n}"],
  ["storage.container_litres", "{litres} L", "{litres} L", "{litres} L"],
  ["storage.container_full", "Container {n}, full", "Lalagyan {n}, puno na", "Butangan {n}, puno na"],
  ["storage.hint", "Tap a container when it's full. Fill now, while there's still pressure in the line.", "Pindutin ang lalagyan kapag puno na. Mag-ipon na habang malakas pa ang tulo.", "Pinduta an butangan kun puno na. Pag-ipon na samtang makusog pa an tubig ha tubo."],
  ["storage.done", "That's enough for 24 hours. No need to store more.", "Sapat na iyan para sa 24 oras. Hindi na kailangang mag-ipon pa.", "Igo na iton para ha 24 oras. Diri na kinahanglan mag-ipon pa."],

  // Backup sources
  ["runout.title", "If you run out", "Kung maubusan ka", "Kun maubusan ka"],
  ["runout.nearest", "Plan {letter} · try this first", "Plan {letter} · subukan muna ito", "Plan {letter} · utroha anay ini"],
  ["runout.see_all", "See all {n} backup sources", "Tingnan ang {n} na reserbang mapagkukunan", "Kitaa an {n} nga reserba nga kuhaan"],
  ["source.safe", "Safe to drink", "Ligtas inumin", "Luwas imnon"],
  ["source.boil", "Boil before drinking", "Pakuluan bago inumin", "Pabukala antes imnon"],
  ["source.washing", "Washing only", "Panghugas lang", "Panhugas la"],
  ["source.walk", "{n} min walk", "{n} minutong lakad", "{n} minuto nga lakat"],
  ["source.free", "Free", "Libre", "Libre"],
  ["source.cost", "₱{price} per {litres} L", "₱{price} bawat {litres} L", "₱{price} kada {litres} L"],
  ["source.checked_by", "Checked by {name}, barangay water captain · {time}", "Sinuri ni {name}, barangay water captain · {time}", "Gin-check ni {name}, barangay water captain · {time}"],
  ["source.reported", "{name} · {time}", "{name} · {time}", "{name} · {time}"],
  ["source.live.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["source.live.open_stock", "Open · has stock", "Bukas · may stock", "Bukas · may stock"],
  ["source.live.queue", "Flowing · queue of ~{n}", "Dumadaloy · pila ng ~{n}", "Nagawas · linya nga ~{n}"],
  ["source.live.scheduled", "Scheduled {time}", "Nakaiskedyul {time}", "Naka-iskedyul {time}"],
  ["source.live.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["source.live.dry", "Dry", "Tuyo", "Hubas"],
  ["source.simulated", "Simulated · sample entry, not yet checked", "Halimbawa lang · hindi pa nasusuri", "Halimbawa la · diri pa nasusi"],
  ["source.bring","Bring containers", "Magdala ng lalagyan", "Pagdara hin butangan"],
  ["sources.title", "Your backup water plan", "Ang iyong reserbang plano sa tubig", "An imo reserba nga plano ha tubig"],
  ["sources.map_loading", "Loading the map…", "Kinukuha ang mapa…", "Ginkukuha an mapa…"],
  ["sources.map_label", "Map of backup water near {barangay}", "Mapa ng reserbang tubig malapit sa {barangay}", "Mapa han reserba nga tubig hirani ha {barangay}"],
  ["sources.map_your_barangay", "Your barangay", "Ang barangay mo", "An imo barangay"],
  ["sources.map_you", "You are here", "Nandito ka", "Aadi ka"],
  ["sources.map_nearest", "Plan {letter} · nearest on the map", "Plan {letter} · pinakamalapit sa mapa", "Plan {letter} · pinakahirani ha mapa"],
  ["sources.map_distance_m", "About {m} m away", "Mga {m} m ang layo", "Mga {m} m an kahirayo"],
  ["sources.map_distance_km", "About {km} km away", "Mga {km} km ang layo", "Mga {km} km an kahirayo"],
  ["sources.map_from_you", "in a straight line from you", "tuwid na linya mula sa iyo", "tadong nga linya tikang ha imo"],
  ["sources.map_from_barangay", "in a straight line from the centre of your barangay", "tuwid na linya mula sa gitna ng barangay mo", "tadong nga linya tikang ha butnga han imo barangay"],
  ["sources.map_use_location", "Use my location", "Gamitin ang lokasyon ko", "Gamita an akon lokasyon"],
  ["sources.map_locating", "Finding where you are…", "Hinahanap kung nasaan ka…", "Ginbibilng kun hain ka…"],
  ["sources.map_location_failed", "We couldn't find your location. The map uses the centre of your barangay.", "Hindi namin makita ang lokasyon mo. Gitna ng barangay mo ang gamit ng mapa.", "Diri namon makita an imo lokasyon. An butnga han imo barangay an gamit han mapa."],
  ["route.show", "Show walking route", "Ipakita ang daan papunta", "Ipakita an dalan pakadto"],
  ["route.loading", "Finding a walking route…", "Hinahanap ang daan…", "Ginbibilng an dalan…"],
  ["route.failed", "We couldn't get a walking route. Check your signal and try again.", "Hindi makuha ang daan. Tingnan ang signal at subukan ulit.", "Diri makuha an dalan. Kitaa an signal ngan utroha."],
  ["route.title", "Walking route to Plan {letter}", "Daan papunta sa Plan {letter}", "Dalan pakadto ha Plan {letter}"],
  ["route.total", "{distance} · about {min} min walk", "{distance} · mga {min} minutong lakad", "{distance} · mga {min} minuto nga lakat"],
  ["route.done", "Done", "Tapos na", "Human na"],
  ["sources.map_offline", "The map needs internet. The list below still works.", "Kailangan ng internet ang mapa. Gumagana pa rin ang listahan sa ibaba.", "Kinahanglan hin internet an mapa. Nagana pa gihapon an listahan ha ubos."],
  ["sources.map_none", "We don't have map locations for these sources yet.", "Wala pa kaming lokasyon sa mapa ng mga ito.", "Waray pa kami lokasyon ha mapa hini."],
  ["sources.sub", "{barangay}. Ranked by safety first, then walking time, then cost.", "{barangay}. Inayos ayon sa kaligtasan, saka layo ng lakad, saka presyo.", "{barangay}. Ginhan-ay sumala han kaluwasan, katapos kahirayo han lakat, katapos presyo."],
  ["sources.legend_a", "Bars show the full round trip, queue included. The mark is ", "Ipinapakita ng guhit ang buong balikan, kasama ang pila. Ang marka ay ", "Ginpapakita han linya an bug-os nga balikan, upod an linya. An marka amo an "],
  ["sources.legend_b", "{min} minutes", "{min} minuto", "{min} minuto"],
  ["sources.legend_c", ", the WHO/UNICEF line for basic access.", ", ang pamantayan ng WHO/UNICEF para sa batayang access.", ", an sukol han WHO/UNICEF para ha basic nga access."],
  ["sources.plan_label", "Plan {letter}:", "Plan {letter}:", "Plan {letter}:"],
  ["sources.round_trip", "Round trip ≈ {n} min", "Balikan ≈ {n} min", "Balikan ≈ {n} min"],
  ["sources.over_line", "Round trip ≈ {n} min, over the {jmp}-min line", "Balikan ≈ {n} min, lampas sa {jmp}-min na guhit", "Balikan ≈ {n} min, labaw ha {jmp}-min nga linya"],

  // History tab (no wireframe yet)
  ["history.title", "History", "Kasaysayan", "Kasaysayan"],
  ["history.empty", "Past interruptions in your barangay will show here.", "Dito makikita ang mga nakaraang pagkawala ng tubig sa barangay mo.", "Dinhi makikita an mga naglabay nga pagkawara han tubig ha imo barangay."],

  // Barangay + language picker
  ["settings.title", "Your barangay", "Ang iyong barangay", "An imo barangay"],
  ["settings.sub", "We'll remember it on this phone.", "Tatandaan namin ito sa phone na ito.", "Hinunumdoman namon ini hini nga phone."],
  ["settings.search_label", "Search your barangay", "Hanapin ang iyong barangay", "Bilnga an imo barangay"],
  ["settings.search_scope", "Catbalogan City only, for now.", "Catbalogan City lang muna.", "Catbalogan City la anay."],
  ["settings.search_placeholder", "Type a name or number", "I-type ang pangalan o numero", "Isurat an ngaran o numero"],
  ["settings.no_match", "No barangay in Catbalogan matches “{query}”. Check the spelling or try the number.", "Walang barangay sa Catbalogan na tugma sa “{query}”. Suriin ang baybay o subukan ang numero.", "Waray barangay ha Catbalogan nga tugma ha “{query}”. Kitaa an pagbaybay o utroha an numero."],
  ["settings.open_list", "Show all barangays", "Ipakita ang lahat ng barangay", "Ipakita an ngatanan nga barangay"],
  ["settings.close_list", "Close the list", "Isara ang listahan", "Sirhi an listahan"],
  ["settings.language","Language", "Wika", "Yinaknan"],
  ["settings.save", "Save", "I-save", "I-save"],
  ["lang.waray", "Waray", "Waray", "Waray"],
  ["lang.filipino", "Filipino", "Filipino", "Filipino"],
  ["lang.english", "English", "English", "English"],

  // Barangay water captain
  ["captain.role", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}"],
  ["captain.greeting_morning", "Good morning, {name}", "Magandang umaga, {name}", "Maupay nga aga, {name}"],
  ["captain.greeting_afternoon", "Good afternoon, {name}", "Magandang hapon, {name}", "Maupay nga kulop, {name}"],
  ["captain.greeting_evening", "Good evening, {name}", "Magandang gabi, {name}", "Maupay nga gab-i, {name}"],
  ["captain.up_to_date", "Up to date · {time}", "Updated · {time}", "Updated · {time}"],
  ["captain.piped_off", "Piped water is off", "Patay ang tubig sa tubo", "Patay an tubig ha tubo"],
  ["captain.piped_on", "Piped water is on", "May tubig sa tubo", "May tubig ha tubo"],
  ["captain.since", "Since {time} · {cause}", "Mula {time} · {cause}", "Tikang {time} · {cause}"],
  ["captain.expected_back", "Expected back", "Inaasahang babalik", "Ginlalaoman nga mabalik"],
  ["captain.relies_on", "Your barangay relies on", "Umaasa ang barangay mo sa", "Nasandig an imo barangay ha"],
  ["captain.n_sources", "{n} sources", "{n} mapagkukunan", "{n} nga kuhaan"],
  ["captain.round_title", "Morning round", "Pag-ikot sa umaga", "Paglibot ha aga"],
  ["captain.round_progress", "{done} of {total} checked", "{done} sa {total} nasuri", "{done} han {total} na-check"],
  ["captain.checked_at", "Checked {time}", "Nasuri {time}", "Na-check {time}"],
  ["captain.not_checked", "Not checked", "Hindi pa nasusuri", "Diri pa na-check"],
  ["captain.plan_line", "Plan {letter} · {safety}", "Plan {letter} · {safety}", "Plan {letter} · {safety}"],
  ["captain.toast", "Saved on this phone. It is not sent yet.", "Nase-save sa teleponong ito. Hindi pa ito naipapadala.", "Nase-save hini nga telepono. Diri pa ini ginpadara."],
  ["captain.updates_title", "Your updates today", "Ang iyong mga update ngayon", "An imo mga update yana"],
  ["captain.delivered", "updates delivered", "update na naihatid", "update nga naihatod"],
  ["captain.to_working", "went to a working source", "pumunta sa gumaganang mapagkukunan", "kinadto ha nagana nga kuhaan"],
  ["captain.more_thanks", "+ {n} more thank-yous", "+ {n} pang pasasalamat", "+ {n} pa nga salamat"],
  ["seg.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["seg.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["seg.dry", "Dry", "Tuyo", "Hubas"],

  // CWD operator dashboard
  ["operator.org", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant"],
  ["operator.tab_monitor", "Monitor", "Monitor", "Monitor"],
  ["operator.tab_risk", "Predictions", "Predictions", "Predictions"],
  ["operator.tab_log", "Readings log", "Talaan ng readings", "Listahan han readings"],
  ["operator.tab_events", "Events", "Mga pangyayari", "Mga hitabo"],
  ["operator.tab_thresholds", "Thresholds", "Mga hangganan", "Mga utlan"],
  ["operator.shift", "Shift: {name} · {hours}", "Shift: {name} · {hours}", "Shift: {name} · {hours}"],
  ["operator.title", "{intake} · {day} {time}", "{intake} · {day} {time}", "{intake} · {day} {time}"],
  ["operator.intake_label", "Water intake", "Pinagkukunan ng tubig", "Kuhaan han tubig"],
  ["operator.event_open", "Event {id} open", "Bukas ang event {id}", "Bukas an event {id}"],
  ["operator.readings_pill", "Plant readings", "Readings ng planta", "Readings han planta"],
  ["operator.readings_sub", "Logged by you, hourly", "Ikaw ang nagtatala, kada oras", "Ikaw an nagsusurat, kada oras"],
  ["operator.readings_due", "Last {last} · {due} due", "Huli {last} · {due} ang susunod", "Katapusan {last} · {due} an sunod"],
  ["operator.rain_pill", "Rainfall over the catchment", "Ulan sa catchment", "Uran ha catchment"],
  ["operator.rain_sub", "Open-Meteo, automatic", "Open-Meteo, awtomatiko", "Open-Meteo, awtomatiko"],
  ["operator.raw", "Raw turbidity", "Raw turbidity", "Raw turbidity"],
  ["operator.over_limit", "Over limit", "Lampas sa limit", "Labaw ha limit"],
  ["operator.raw_over", "Above the {limit} NTU limit: treat through the clarifier", "Lampas sa {limit} NTU na limit: linisin sa clarifier", "Labaw ha {limit} NTU nga limit: limpyohi ha clarifier"],
  ["operator.raw_under", "Under the {limit} NTU limit", "Mas mababa sa {limit} NTU na limit", "Ubos han {limit} NTU nga limit"],
  ["operator.raw_shutoff", "{limit} NTU or more since {time}: temporary shut-off at this source", "{limit} NTU pataas mula {time}: pansamantalang sarado ang pinagkukunan", "{limit} NTU pataas tikang {time}: temporaryo nga sirado an kuhaan"],
  ["operator.shutoff", "Shut-off", "Sarado", "Sirado"],
  ["operator.kulador_only", "Treated turbidity, clarifier flow and the reservoir are logged at Kulador only.", "Sa Kulador lang itinatala ang treated turbidity, daloy ng clarifier at reservoir.", "Ha Kulador la ginsusurat an treated turbidity, agos han clarifier ngan reservoir."],
  ["operator.treated", "Treated turbidity", "Treated turbidity", "Treated turbidity"],
  ["operator.treated_under", "Under the {limit} NTU limit", "Mas mababa sa {limit} NTU na limit", "Ubos han {limit} NTU nga limit"],
  ["operator.treated_over", "Over the {limit} NTU limit", "Lampas sa {limit} NTU na limit", "Labaw ha {limit} NTU nga limit"],
  ["operator.clarifier", "Clarifier flow", "Daloy ng clarifier", "Agos han clarifier"],
  ["operator.clarifier_cut", "Capacity ≈ {cap} L/s · cut back", "Kapasidad ≈ {cap} L/s · binawasan", "Kapasidad ≈ {cap} L/s · ginkunhuran"],
  ["operator.clarifier_full", "Capacity ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s"],
  ["operator.reservoir", "Reservoir", "Reservoir", "Reservoir"],
  ["operator.reservoir_trend", "Falling ~{n} points an hour", "Bumababa ~{n} puntos kada oras", "Nauubos ~{n} puntos kada oras"],
  ["unit.ntu", "NTU", "NTU", "NTU"],
  ["unit.lps", "L/s", "L/s", "L/s"],
  ["unit.pct", "%", "%", "%"],
  ["operator.chart_turbidity", "Raw turbidity at {intake}, last 24 hours", "Raw turbidity sa {intake}, nakaraang 24 oras", "Raw turbidity ha {intake}, naglabay nga 24 oras"],
  ["operator.simulated", "Simulated", "Simulated", "Simulated"],
  ["operator.no_readings", "No readings logged in the 24 hours before this time.", "No readings logged in the 24 hours before this time.", "No readings logged in the 24 hours before this time."],
  ["operator.chart_units", "NTU · hourly", "NTU · kada oras", "NTU · kada oras"],
  ["operator.plant_limit", "Shut-off {limit} NTU", "Sarado sa {limit} NTU", "Sirado ha {limit} NTU"],
  ["operator.now_value", "{value} now", "{value} ngayon", "{value} yana"],
  ["operator.chart_rain", "Rainfall over the Antiao catchment", "Ulan sa Antiao catchment", "Uran ha Antiao catchment"],
  ["operator.rain_summary", "mm per hour · {mm} mm since {time} · {days} dry-spell days", "mm kada oras · {mm} mm mula {time} · {days} araw na tagtuyot", "mm kada oras · {mm} mm tikang {time} · {days} ka adlaw nga hulaw"],
  ["operator.log_title", "Log the {time} reading · {intake}", "Itala ang reading ng {time} · {intake}", "Isurat an reading han {time} · {intake}"],
  ["operator.last_logged", "Last logged {time} by you", "Huling naitala {time} mo", "Katapusan nga ginsurat {time} nimo"],
  ["operator.field_raw", "Raw turbidity (NTU)", "Raw turbidity (NTU)", "Raw turbidity (NTU)"],
  ["operator.field_treated", "Treated turbidity (NTU)", "Treated turbidity (NTU)", "Treated turbidity (NTU)"],
  ["operator.field_clarifier", "Clarifier flow (L/s)", "Daloy ng clarifier (L/s)", "Agos han clarifier (L/s)"],
  ["operator.field_reservoir", "Reservoir (%)", "Reservoir (%)", "Reservoir (%)"],
  ["operator.field_status", "Plant status", "Kalagayan ng planta", "Kahimtang han planta"],
  ["plant.normal", "Normal", "Normal", "Normal"],
  ["plant.degraded", "Reduced output", "Bawas na output", "Gin-kunhuran nga output"],
  ["plant.shutdown", "Shut down", "Nakasara", "Sirado"],
  ["operator.save", "Save reading", "I-save ang reading", "I-save an reading"],
  ["operator.save_hint", "Saved on this device. Sending starts once the server is connected.", "Nase-save sa device na ito. Magsisimula ang pagpapadala kapag nakakonekta na ang server.", "Nase-save hini nga device. Magtitikang an pagpadara kun nakakonekta na an server."],
  ["operator.saved", "Saved on this device. {n} waiting to send.", "Naka-save sa device na ito. {n} naghihintay maipadala.", "Naka-save hini nga device. {n} naghuhulat ipadara."],
  ["operator.invalid", "Check the highlighted numbers.", "Suriin ang mga numerong naka-highlight.", "I-check an mga numero nga naka-highlight."],
  ["operator.err_number", "Enter a number, 0 or more", "Maglagay ng numero, 0 pataas", "Pagbutang hin numero, 0 pataas"],
  ["operator.err_pct", "Enter a number from 0 to 100", "Maglagay ng numero mula 0 hanggang 100", "Pagbutang hin numero tikang 0 tubtob 100"],
  ["detector.label", "Disruption detector", "Disruption detector", "Disruption detector"],
  ["detector.turbidity", "Turbidity spike", "Biglang paglabo", "Kalit nga paglubog"],
  ["detector.matched", "{n} of {total} signals match. You confirmed it at {time}.", "{n} sa {total} senyales ang tugma. Kinumpirma mo ito noong {time}.", "{n} han {total} nga senyales an tugma. Gin-kumpirma mo ini han {time}."],
  ["detector.sig_raw", "Caramayon I at {limit} NTU or more since {time}: source shut off", "Caramayon I sa {limit} NTU pataas mula {time}: sarado ang pinagkukunan", "Caramayon I ha {limit} NTU pataas tikang {time}: sirado an kuhaan"],
  ["detector.sig_rain", "{mm} mm of rain in {hours} hours over the catchment", "{mm} mm na ulan sa loob ng {hours} oras sa catchment", "{mm} mm nga uran ha sulod han {hours} oras ha catchment"],
  ["detector.sig_clarifier", "Clarifier cut from {from} to {to} L/s", "Clarifier binawasan mula {from} hanggang {to} L/s", "Clarifier ginkunhuran tikang {from} ngadto {to} L/s"],
  ["detector.low_source", "Low source level", "Mababang lebel ng pinagkukunan", "Ubos nga lebel han kuhaan"],
  ["detector.low_source_note", "{n} of {total} · no dry spell, intake normal", "{n} sa {total} · walang tagtuyot, normal ang intake", "{n} han {total} · waray hulaw, normal an intake"],
  ["detector.repair", "Repair work", "Pag-aayos", "Pag-ayad"],
  ["detector.repair_note", "{n} of {total} · nothing scheduled", "{n} sa {total} · walang nakaiskedyul", "{n} han {total} · waray naka-iskedyul"],
  ["detector.window", "Time window residents see", "Oras na nakikita ng mga residente", "Oras nga nakikita han mga residente"],
  ["detector.window_value", "{window} · likely {likely}", "{window} · malamang {likely}", "{window} · posible {likely}"],
  ["detector.adjust", "Adjust", "Baguhin", "Igbag-o"],
  ["detector.next", "Next resident update due {time}. You'll be reminded at {remind}.", "Susunod na update sa residente bago mag-{time}. Ipapaalala sa iyo sa {remind}.", "Sunod nga update ha residente antes han {time}. Pahinumdoman ka ha {remind}."],
  ["operator.footnote", "CWD 2022 WSP: {limit} NTU limit (pp.43–44) · {shut} NTU shut-off, Caramayon I (p.43) · ≈{cap} L/s clarifier (p.16)", "CWD 2022 WSP: {limit} NTU na limit (pp.43–44) · sarado sa {shut} NTU, Caramayon I (p.43) · ≈{cap} L/s clarifier (p.16)", "CWD 2022 WSP: {limit} NTU nga limit (pp.43–44) · sirado ha {shut} NTU, Caramayon I (p.43) · ≈{cap} L/s clarifier (p.16)"],

  // Admin placeholder (spec 07)
  ["admin.org", "Catbalogan CDRRMO", "Catbalogan CDRRMO", "Catbalogan CDRRMO"],

  // Live dashboard (spec 07, /lgu/live). LGU screens render English only (spec 08 Decisions),
  // so the Filipino/Waray columns repeat the English and need no review.
  ["lgu.tab_live", "Live status", "Live status", "Live status"],
  // Live dashboard (LGU, English only by spec 08). FIL/WAR below are DRAFTS for native review (see NEEDS_REVIEW); they only show if the screen ever leaves English.
  ["live.title", "Live status", "Live na status", "Live nga kahimtang"],
  ["live.live", "Live · last update {time}", "Live · huling update {time}", "Live · urhi nga update {time}"],
  ["live.live_now", "Live", "Live", "Live"],
  ["live.connecting", "Connecting…", "Kumokonekta…", "Nag-iikonekta…"],
  ["live.dropped", "Not live since {time}", "Hindi live mula {time}", "Diri live tikang {time}"],
  ["live.dropped_never", "Not live", "Hindi live", "Diri live"],
  ["live.dropped_body", "The live connection dropped. What you see was true at {time}. Tap Refresh when you're back online.", "Naputol ang live na koneksyon. Totoo ang nakikita mo noong {time}. Pindutin ang Refresh para sa pinakabago.", "Naputol an live nga koneksyon. Tinuod an nakikita mo han {time}. Pindota an Refresh para ha pinakabag-o."],
  ["live.refresh", "Refresh", "I-refresh", "I-refresh"],
  ["live.levels_title", "Signal level across {n} barangays", "Antas ng signal sa {n} barangay", "Lebel han signal ha {n} nga barangay"],
  ["live.level", "Level {n}", "Antas {n}", "Lebel {n}"],
  ["live.level_count", "{n} barangays", "{n} barangay", "{n} nga barangay"],
  ["live.level_count_one", "1 barangay", "1 barangay", "1 nga barangay"],
  ["live.grid_title", "Barangays", "Mga barangay", "Mga barangay"],
  ["live.filter_label", "Show barangays", "Ipakita ang mga barangay", "Ipakita an mga barangay"],
  ["live.filter_open", "Open", "Bukas", "Bukas"],
  ["live.filter_resolved", "Resolved", "Tapos na", "Human na"],
  ["live.filter_all", "All", "Lahat", "Ngatanan"],
  ["live.filter_count", "{label} · {n}", "{label} · {n}", "{label} · {n}"],
  ["live.status.predicted", "Predicted", "Hinulaan", "Gin-predict"],
  ["live.status.confirmed", "Confirmed", "Kumpirmado", "Kumpirmado"],
  ["live.status.deployed", "Response deployed", "Naipadala na ang tugon", "Naipadara na an tugon"],
  ["live.status.notified", "Residents notified", "Naabisuhan ang mga residente", "Naabisohan an mga residente"],
  ["live.status.resolved", "Resolved", "Tapos na", "Human na"],
  ["live.last_event", "last event {time}", "huling event {time}", "urhi nga event {time}"],
  ["live.resident_confirmed_tag", "Residents confirmed water is back", "Kinumpirma ng mga residente na bumalik ang tubig", "Gin-kumpirma han mga residente nga nabalik an tubig"],
  ["live.empty_filter", "No barangays here right now.", "Walang barangay dito ngayon.", "Waray barangay dinhi yana."],
  ["live.feed_title", "Live events", "Mga live na event", "Mga live nga event"],
  ["live.feed_sub", "Newest first", "Pinakabago muna", "Pinakabag-o anay"],
  ["live.feed_empty", "Waiting for the next event…", "Hinihintay ang susunod na event…", "Ginhihulat an sunod nga event…"],
  ["live.all_barangays", "All served barangays", "Lahat ng sineserbisyuhang barangay", "Ngatanan nga barangay nga ginsisilbihan"],
  ["live.heads_up_tag", "heads-up", "paalala", "pahinumdom"],
  ["live.event_line", "{event} · {barangay}", "{event} · {barangay}", "{event} · {barangay}"],
  ["live.event.predicted", "Disruption predicted", "Hinulaang pagkaputol", "Gin-predict nga pagkaputol"],
  ["live.event.confirmed", "Disruption confirmed", "Kumpirmado ang pagkaputol", "Kumpirmado an pagkaputol"],
  ["live.event.deployed", "Response deployed", "Naipadala ang tugon", "Naipadara an tugon"],
  ["live.event.notified", "Residents notified", "Naabisuhan ang mga residente", "Naabisohan an mga residente"],
  ["live.event.resident_confirmed", "Residents confirmed water is back", "Kinumpirma ng mga residente na bumalik ang tubig", "Gin-kumpirma han mga residente nga nabalik an tubig"],
  ["live.event.resolved", "Water restored", "Naibalik ang tubig", "Nabalik an tubig"],
  ["live.sample", "Sample data. The live feed is simulated until the server is connected.", "Sample na data. Simulasyon ang live feed hanggang makakonekta ang server.", "Sample nga data. Simulasyon an live feed tubtob makakonekta an server."],

  // LGU allocation (spec 06, wireframe p.10)
  ["lgu.tab_priorities", "Set priorities", "Itakda ang prayoridad", "Igbutang an prayoridad"],
  ["lgu.tab_records", "Event records", "Talaan ng mga event", "Listahan han mga event"],
  ["lgu.tab_plan", "Planning", "Planning", "Planning"],
  ["lgu.who_value", "{n} people (estimate)", "{n} people (estimate)", "{n} people (estimate)"],
  ["lgu.affected_sub_clusters", "{clusters} settlement clusters in {barangays} barangays (estimate)", "{clusters} settlement clusters in {barangays} barangays (estimate)", "{clusters} settlement clusters in {barangays} barangays (estimate)"],
  ["lgu.need_pts", "{n} need pts", "{n} need pts", "{n} need pts"],
  ["lgu.rows_empty_title", "No population data yet", "No population data yet", "No population data yet"],
  ["lgu.rows_empty_body", "Priorities appear once the settlement clusters are generated from PSA 2020 and WorldPop 2020 (spec 10).", "Priorities appear once the settlement clusters are generated from PSA 2020 and WorldPop 2020 (spec 10).", "Priorities appear once the settlement clusters are generated from PSA 2020 and WorldPop 2020 (spec 10)."],
  ["lgu.need_why_title", "What are need points?", "What are need points?", "What are need points?"],
  ["lgu.need_why_body", "A heuristic in people-equivalents, not a standard. Each person counts 1. A person with no safe water within {jmp} min counts {access}. Each elderly or PWD resident (estimate) adds {vuln}. A health station or evacuation center adds {fac}. Everything grows up to x{max} after a day without water. You can still move any row; each move is logged.", "A heuristic in people-equivalents, not a standard. Each person counts 1. A person with no safe water within {jmp} min counts {access}. Each elderly or PWD resident (estimate) adds {vuln}. A health station or evacuation center adds {fac}. Everything grows up to x{max} after a day without water. You can still move any row; each move is logged.", "A heuristic in people-equivalents, not a standard. Each person counts 1. A person with no safe water within {jmp} min counts {access}. Each elderly or PWD resident (estimate) adds {vuln}. A health station or evacuation center adds {fac}. Everything grows up to x{max} after a day without water. You can still move any row; each move is logged."],
  ["lgu.reason_list", "Reasons", "Reasons", "Reasons"],
  ["lgu.map_hotspots", "Need hotspots by settlement cluster", "Need hotspots by settlement cluster", "Need hotspots by settlement cluster"],
  ["lgu.cluster_pin_label", "{name}: priority {rank}, {people} people. Show in list", "{name}: priority {rank}, {people} people. Show in list", "{name}: priority {rank}, {people} people. Show in list"],
  ["lgu.legend_size", "Bigger circle = more people", "Bigger circle = more people", "Bigger circle = more people"],
  ["lgu.legend_shade", "Darker = more need", "Darker = more need", "Darker = more need"],
  ["lgu.legend_ring", "Red ring = no safe water within {jmp} min", "Red ring = no safe water within {jmp} min", "Red ring = no safe water within {jmp} min"],
  ["lgu.map_source", "People: PSA 2020 census, spread by WorldPop 2020 (estimate)", "People: PSA 2020 census, spread by WorldPop 2020 (estimate)", "People: PSA 2020 census, spread by WorldPop 2020 (estimate)"],
  ["lgu.map_numbers", "Numbers and the strip show the top 10 clusters in the current order. Circles are cluster centres (estimate).", "Numbers and the strip show the top 10 clusters in the current order. Circles are cluster centres (estimate).", "Numbers and the strip show the top 10 clusters in the current order. Circles are cluster centres (estimate)."],
  ["lgu.map_strip_top", "Top 10 clusters by priority", "Top 10 clusters by priority", "Top 10 clusters by priority"],
  ["lgu.map_served_first", "Served first", "Served first", "Served first"],
  ["lgu.stat_clusters", "Settlement clusters (estimate)", "Settlement clusters (estimate)", "Settlement clusters (estimate)"],
  ["lgu.stat_people", "People (PSA 2020 census, spread by WorldPop 2020)", "People (PSA 2020 census, spread by WorldPop 2020)", "People (PSA 2020 census, spread by WorldPop 2020)"],
  ["lgu.stat_no_safe", "People with no safe water within {jmp} min", "People with no safe water within {jmp} min", "People with no safe water within {jmp} min"],
  ["lgu.safe_basis", "Based on {n} safe sources with a known location (OpenStreetMap, WSP). Each newly mapped source can lower this number.", "Based on {n} safe sources with a known location (OpenStreetMap, WSP). Each newly mapped source can lower this number.", "Based on {n} safe sources with a known location (OpenStreetMap, WSP). Each newly mapped source can lower this number."],
  ["lgu.stat_vulnerable_est", "Elderly or PWD (estimate)", "Elderly or PWD (estimate)", "Elderly or PWD (estimate)"],
  ["lgu.stat_facilities_n", "Critical facilities", "Critical facilities", "Critical facilities"],
  ["lgu.truck_plan_title", "Water truck plan", "Water truck plan", "Water truck plan"],
  ["lgu.truck_show", "Show truck route", "Show truck route", "Show truck route"],
  ["lgu.truck_hide", "Hide truck route", "Hide truck route", "Hide truck route"],
  ["lgu.truck_stop", "Stop {n}", "Stop {n}", "Stop {n}"],
  ["lgu.truck_stop_line", "Water for {people} people · {litres} L", "Water for {people} people · {litres} L", "Water for {people} people · {litres} L"],
  ["lgu.truck_capped", "more people live nearby than one trip can serve", "more people live nearby than one trip can serve", "more people live nearby than one trip can serve"],
  ["lgu.truck_people_total", "People given a day's drinking water", "People given a day's drinking water", "People given a day's drinking water"],
  ["lgu.truck_litres_total", "Water loaded", "Water loaded", "Water loaded"],
  ["lgu.truck_litres_value", "{used} of {cap} L", "{used} of {cap} L", "{used} of {cap} L"],
  ["lgu.truck_unmet", "Still without safe water within {jmp} min after the trucks", "Still without safe water within {jmp} min after the trucks", "Still without safe water within {jmp} min after the trucks"],
  ["lgu.truck_no_access_total", "People without safe water within {jmp} min (before trucks)", "People without safe water within {jmp} min (before trucks)", "People without safe water within {jmp} min (before trucks)"],
  ["lgu.truck_empty", "No stops yet: this needs population data.", "No stops yet: this needs population data.", "No stops yet: this needs population data."],
  ["lgu.truck_loading", "Finding the road route…", "Finding the road route…", "Finding the road route…"],
  ["lgu.truck_road", "Route follows roads (OpenStreetMap routing).", "Route follows roads (OpenStreetMap routing).", "Route follows roads (OpenStreetMap routing)."],
  ["lgu.truck_straight", "Road routing is unavailable, so dashed straight lines show the visit order, not roads.", "Road routing is unavailable, so dashed straight lines show the visit order, not roads.", "Road routing is unavailable, so dashed straight lines show the visit order, not roads."],
  ["lgu.truck_depot", "Depot", "Depot", "Depot"],
  ["lgu.truck_note", "Each trip carries an equal share of the truck water. A stop serves people within a {m} m walk, at {lpp} L per person per day.", "Each trip carries an equal share of the truck water. A stop serves people within a {m} m walk, at {lpp} L per person per day.", "Each trip carries an equal share of the truck water. A stop serves people within a {m} m walk, at {lpp} L per person per day."],
  ["lgu.truck_marker", "Stop {n}: {label}", "Stop {n}: {label}", "Stop {n}: {label}"],
  ["lgu.warn_title", "Early warning by need", "Early warning by need", "Early warning by need"],
  ["lgu.warn_body", "Signal level {n} or higher: high-need clusters are warned now, the rest when you confirm.", "Signal level {n} or higher: high-need clusters are warned now, the rest when you confirm.", "Signal level {n} or higher: high-need clusters are warned now, the rest when you confirm."],
  ["lgu.warn_now", "Warn now (prediction)", "Warn now (prediction)", "Warn now (prediction)"],
  ["lgu.warn_later", "Warn at confirmation", "Warn at confirmation", "Warn at confirmation"],
  ["lgu.warn_group_line", "{name}: {clusters} cluster(s), about {people} people (estimate)", "{name}: {clusters} cluster(s), about {people} people (estimate)", "{name}: {clusters} cluster(s), about {people} people (estimate)"],
  ["lgu.warn_none", "No barangays in this group.", "No barangays in this group.", "No barangays in this group."],
  ["lgu.warn_sms", "SMS preview", "SMS preview", "SMS preview"],
  ["lgu.warn_sms_note", "Uses the longest barangay name, so a real message is never longer.", "Uses the longest barangay name, so a real message is never longer.", "Uses the longest barangay name, so a real message is never longer."],
  ["lgu.warn_chars", "{n}/160 characters", "{n}/160 characters", "{n}/160 characters"],
  ["lgu.warn_send", "Send early warning", "Send early warning", "Send early warning"],
  ["lgu.warn_mock", "Not connected yet: sending needs the backend (handoff #12). Nothing was sent.", "Not connected yet: sending needs the backend (handoff #12). Nothing was sent.", "Not connected yet: sending needs the backend (handoff #12). Nothing was sent."],
  ["plan.title", "Where people lack safe water", "Where people lack safe water", "Where people lack safe water"],
  ["plan.sub", "Shows where a permanent safe source would help most, with or without an event.", "Shows where a permanent safe source would help most, with or without an event.", "Shows where a permanent safe source would help most, with or without an event."],
  ["plan.map_title", "Safe water access by settlement cluster", "Safe water access by settlement cluster", "Safe water access by settlement cluster"],
  ["plan.total_label", "People with no safe water within {jmp} min", "People with no safe water within {jmp} min", "People with no safe water within {jmp} min"],
  ["plan.sites_title", "Best places for a new source", "Best places for a new source", "Best places for a new source"],
  ["plan.site_line", "Site {n} · near {label} · +{people} people within {jmp} min", "Site {n} · near {label} · +{people} people within {jmp} min", "Site {n} · near {label} · +{people} people within {jmp} min"],
  ["plan.sites_empty", "No sites yet: this needs population data.", "No sites yet: this needs population data.", "No sites yet: this needs population data."],
  ["plan.note", "Sites are cluster centres; check land, water source and cost before building.", "Sites are cluster centres; check land, water source and cost before building.", "Sites are cluster centres; check land, water source and cost before building."],
  ["plan.legend_gap", "Red ring and coral fill = no safe water within {jmp} min (bigger = more people)", "Red ring and coral fill = no safe water within {jmp} min (bigger = more people)", "Red ring and coral fill = no safe water within {jmp} min (bigger = more people)"],
  ["plan.legend_ok", "Faint blue = safe water within {jmp} min", "Faint blue = safe water within {jmp} min", "Faint blue = safe water within {jmp} min"],
  ["plan.legend_site", "Star = suggested site", "Star = suggested site", "Star = suggested site"],
  ["plan.site_marker", "Site {n}: near {label}, +{people} people within {jmp} min", "Site {n}: near {label}, +{people} people within {jmp} min", "Site {n}: near {label}, +{people} people within {jmp} min"],
  ["lgu.no_event", "No open event", "No open event", "No open event"],
  ["lgu.none_open_title", "No disruption is open at this time", "No disruption is open at this time", "No disruption is open at this time"],
  ["lgu.none_open_body", "The predictor has not opened a disruption. Nothing to allocate yet.", "The predictor has not opened a disruption. Nothing to allocate yet.", "The predictor has not opened a disruption. Nothing to allocate yet."],
  ["lgu.unserved", "Not on the CWD network", "Not on the CWD network", "Not on the CWD network"],
  ["lgu.first_stop", "First stop: {name}", "First stop: {name}", "First stop: {name}"],
  ["lgu.far_source", "far, over {jmp} min round trip", "far, over {jmp} min round trip", "far, over {jmp} min round trip"],
  ["lgu.window_unknown", "Window not set yet", "Window not set yet", "Window not set yet"],
  ["lgu.confirm_event_title", "The disruption is only predicted", "The disruption is only predicted", "The disruption is only predicted"],
  ["lgu.confirm_event_body", "Confirm it first. Allocation opens once the operator confirms.", "Confirm it first. Allocation opens once the operator confirms.", "Confirm it first. Allocation opens once the operator confirms."],
  ["lgu.confirm_event_button", "Confirm disruption", "Confirm disruption", "Confirm disruption"],
  ["lgu.confirming", "Confirming…", "Confirming…", "Confirming…"],
  ["lgu.event_pill", "Event {id} · {cause}", "Event {id} · {cause}", "Event {id} · {cause}"],
  ["lgu.cause.turbidity", "turbidity spike", "biglang paglabo", "kalit nga paglubog"],
  ["lgu.cause.drought", "low river", "mababang ilog", "hubas nga salog"],
  ["lgu.cause.repair", "pipe repair", "pag-aayos ng tubo", "pag-ayad han tubo"],
  ["lgu.officer_line", "{time} · {name}, CDRRMO", "{time} · {name}, CDRRMO", "{time} · {name}, CDRRMO"],
  ["lgu.title", "Who gets water first?", "Sino ang unang bibigyan ng tubig?", "Hin-o an siyahan nga hatagan hin tubig?"],
  ["lgu.what_happened", "What happened", "Ano ang nangyari", "Ano an nahitabo"],
  ["lgu.headline.turbidity", "Water too turbid to treat", "Sobrang labo ng tubig para linisin", "Sobra kalubog an tubig para limpyohan"],
  ["lgu.headline.drought", "River too low to supply everyone", "Masyadong mababa ang ilog para sa lahat", "Sobra kahubas an salog para ha ngatanan"],
  ["lgu.headline.repair", "Pipes under repair", "Inaayos ang mga tubo", "Ginaayad an mga tubo"],
  ["lgu.flagged_by", "Flagged by {who} at {time}", "Itinala ng {who} noong {time}", "Ginmarkahan han {who} han {time}"],
  ["lgu.who_affected", "Who's affected", "Sino ang apektado", "Hin-o an apektado"],
  ["lgu.expected_back", "Expected back", "Inaasahang babalik", "Ginlalaoman nga mabalik"],
  ["lgu.window_today", "{window} today", "{window} ngayong araw", "{window} yana nga adlaw"],
  ["lgu.most_likely", "Most likely around {time}", "Malamang bandang {time}", "Posible mga {time}"],
  ["lgu.decision_step", "Your decision · step {n} of {total}", "Ang iyong desisyon · hakbang {n} sa {total}", "An imo desisyon · lakang {n} han {total}"],
  ["lgu.decision_title", "Check the order below", "Suriin ang pagkakasunod sa ibaba", "Kitaa an han-ay ha ubos"],
  ["lgu.decision_body", "Check the order, then confirm. Notifying residents and routing trucks starts once the server is connected.", "Suriin ang pagkakasunod, saka kumpirmahin. Magsisimula ang pag-abiso sa residente at pagpapadala ng trak kapag nakakonekta na ang server.", "Usisaha an pagkasunod-sunod, katapos kumpirmaha. Magtitikang an pagpahibaro ha residente ngan pagpadara hin trak kun nakakonekta na an server."],
  ["lgu.decision_done_title", "Order confirmed", "Nakumpirma ang pagkakasunod", "Nakumpirma an han-ay"],
  ["lgu.decision_done_body", "Waiting for the server to notify residents", "Hinihintay ang server para abisuhan ang residente", "Ginhuhulat an server para pahibaruon an residente"],
  ["lgu.priority_title", "Priority order", "Pagkakasunod ng prayoridad", "Han-ay han prayoridad"],
  ["facility.barangay_hall", "Barangay hall", "Barangay hall", "Barangay hall"],
  ["lgu.map_title", "Where the need is", "Where the need is", "Where the need is"],
  ["lgu.map_highest", "Highest priority", "Pinakamataas na prayoridad", "Pinakataas nga prayoridad"],
  ["lgu.map_legend_rule", "1 = served first", "1 = unang bibigyan", "1 = siyahan hatagan"],
  ["lgu.map_offline", "Map tiles need internet. Pins still show where each barangay is.", "Kailangan ng internet ang mapa. Tama pa rin ang mga pin.", "Kinahanglan hin internet an mapa. Husto pa gihapon an mga pin."],
  ["lgu.map_zoom_in", "Zoom in", "Palakihin", "Padakoa"],
  ["lgu.map_zoom_out", "Zoom out", "Paliitin", "Pagutiona"],
  ["lgu.map_fit", "Back to Catbalogan", "Bumalik sa Catbalogan", "Balik ha Catbalogan"],
  ["lgu.map_strip", "Priority by barangay", "Prayoridad bawat barangay", "Prayoridad kada barangay"],
  ["lgu.map_centroids", "Pins are approximate barangay centres (OpenStreetMap).", "Tantiyang sentro ng barangay ang mga pin (OpenStreetMap).", "Banabana nga sentro han barangay an mga pin (OpenStreetMap)."],
  ["facility.health_station", "Health station", "Health station", "Health station"],
  ["facility.school", "School", "Paaralan", "Eskwelahan"],
  ["facility.evacuation_center", "Evacuation center", "Evacuation center", "Evacuation center"],
  ["lgu.reported_not_restored", "Reported not restored", "Iniulat na wala pang tubig", "Ginreport nga waray pa tubig"],
  ["lgu.moved_from", "Moved from #{from}", "Inilipat mula #{from}", "Ginbalhin tikang #{from}"],
  ["lgu.move_up", "Move {name} up", "Itaas ang {name}", "Igtaas an {name}"],
  ["lgu.move_down", "Move {name} down", "Ibaba ang {name}", "Igpaubos an {name}"],
  ["lgu.affected_title", "Affected", "Apektado", "Apektado"],
  ["lgu.stat_barangays", "Barangays", "Barangay", "Barangay"],
  ["lgu.route_title", "Water you can route", "Tubig na maipapadala", "Tubig nga maipapadara"],
  ["lgu.trucks", "LGU trucks", "Trak ng LGU", "Trak han LGU"],
  ["lgu.trucks_value", "{trucks} trucks · {trips} trips each", "{trucks} trak · {trips} biyahe bawat isa", "{trucks} nga trak · {trips} nga biyahe kada usa"],
  ["lgu.truck_water", "Truck water before {time}", "Tubig ng trak bago mag-{time}", "Tubig han trak antes han {time}"],
  ["lgu.litres_approx", "≈ {litres} L", "≈ {litres} L", "≈ {litres} L"],
  ["lgu.partners", "Station partners open", "Bukas na station partner", "Bukas nga station partner"],
  ["lgu.partners_value", "{open} of {total}", "{open} sa {total}", "{open} han {total}"],
  ["lgu.confirm_title", "Confirm and notify", "Kumpirmahin at abisuhan", "Kumpirmaha ngan pahibaruon"],
  ["lgu.confirm_body", "Residents get the status, the time window and their backup plan. Trucks are routed in this order. You can change the plan later; each version is logged.", "Makukuha ng residente ang status, oras, at reserbang plano. Ipapadala ang trak ayon sa ayos na ito. Mababago mo ito mamaya; naitatala ang bawat bersyon.", "Makakarawat an residente han kahimtang, oras, ngan reserba nga plano. Ipapadara an trak sumala hini nga han-ay. Mababag-o mo ini huhuraaw; ginsusurat an kada bersyon."],
  ["lgu.confirm_button", "Confirm priorities as {name}", "Kumpirmahin bilang {name}", "Kumpirmaha sugad nga {name}"],
  ["lgu.changes_none", "Recommended order, no changes.", "Inirekomendang ayos, walang pagbabago.", "Girekomenda nga han-ay, waray pagbag-o."],
  ["lgu.changes_some", "{n} changed from the recommended order.", "{n} ang binago mula sa inirekomendang ayos.", "{n} an ginbag-o tikang ha girekomenda nga han-ay."],
  ["lgu.log_note", "Changes will be saved to the allocation log under your name once the server is connected.", "Maitatala sa allocation log sa ilalim ng pangalan mo ang mga pagbabago kapag nakakonekta na ang server.", "Ginsusurat ha allocation log ilarom han imo ngaran an mga pagbag-o kun nakakonekta na an server."],
  ["lgu.saving", "Saving…", "Sine-save…", "Gin-sesave…"],
  ["lgu.not_connected", "Not sent yet. The server that saves this and notifies residents isn't connected, so nothing has left this screen.", "Hindi pa naipadala. Hindi pa konektado ang server na nagse-save at nag-aabiso, kaya walang lumabas sa screen na ito.", "Diri pa naipadara. Diri pa konektado an server nga nagse-save ngan nagpapahibaro, salit waray gumawas hini nga screen."],
  ["lgu.out_of_order", "That step can't run yet. Finish the step before it first (confirm, then deploy, then notify).", "Hindi pa maaaring gawin ang hakbang na ito. Tapusin muna ang nauna (kumpirma, ipadala, saka abisuhan).", "Diri pa mahimo ini nga lakang. Tapusa anay an nauna (kumpirma, ipadara, ngan pahibaro)."],
  // Event record (spec 06 AC5 + MEM-1, wireframe p.11)
  ["record.download", "Download record", "I-download ang talaan", "I-download an listahan"],
  ["record.closed", "Closed · water restored {time}", "Sarado · bumalik ang tubig {time}", "Sirado · nabalik an tubig {time}"],
  ["record.title", "{id} · {cause}", "{id} · {cause}", "{id} · {cause}"],
  ["record.cause.turbidity", "Turbidity spike", "Biglang paglabo", "Kalit nga paglubog"],
  ["record.cause.drought", "Low river", "Mababang ilog", "Hubas nga salog"],
  ["record.cause.repair", "Pipe repair", "Pag-aayos ng tubo", "Pag-ayad han tubo"],
  ["record.subtitle", "{day} · {start} to {end} · saved automatically when supply returned", "{day} · {start} hanggang {end} · awtomatikong na-save nang bumalik ang tubig", "{day} · {start} tubtob {end} · awtomatiko nga na-save han nabalik an tubig"],
  ["record.hero", "Residents heard from you {diff} sooner than in {month}.", "Mas maaga ng {diff} nakatanggap ng balita ang residente kaysa noong {month}.", "Mas temprano hin {diff} nakarawat hin balita an residente kaysa han {month}."],
  ["record.hero_body", "And the {n} off-network households were on the map this time. In the {month} event they weren't tracked at all.", "At nasa mapa na ngayon ang {n} pamilyang wala sa tubo. Noong {month}, hindi sila nasubaybayan.", "Ngan aada na ha mapa yana an {n} nga pamilya nga waray ha tubo. Han {month}, diri hira nasubay."],
  ["record.notice_label", "Notice to residents after CWD flag", "Abiso sa residente matapos ang marka ng CWD", "Pahibaro ha residente katapos han marka han CWD"],
  ["record.notice_prev", "{month} event: {value}", "Event noong {month}: {value}", "Event han {month}: {value}"],
  ["record.stat_duration", "Duration", "Tagal", "Kadugayon"],
  ["record.stat_barangays", "Barangays", "Barangay", "Barangay"],
  ["record.stat_households", "Households", "Pamilya", "Pamilya"],
  ["record.stat_truck", "Truck water delivered", "Naihatid na tubig ng trak", "Naihatod nga tubig han trak"],
  ["record.stat_vs", "Restored vs likely time", "Pagbalik kumpara sa inaasahan", "Pagbalik kumpara ha ginlaoman"],
  ["record.early", "{n} min early", "{n} min mas maaga", "{n} min mas temprano"],
  ["record.late", "{n} min late", "{n} min huli", "{n} min ulahi"],
  ["record.litres", "{litres} L", "{litres} L", "{litres} L"],
  ["record.what_happened", "What happened", "Ano ang nangyari", "Ano an nahitabo"],
  ["event.predicted", "Raw turbidity passed {limit} NTU", "Lumampas sa {limit} NTU ang raw turbidity", "Linmapos ha {limit} NTU an raw turbidity"],
  ["event.confirmed", "CWD confirmed a turbidity spike · {actor}", "Kinumpirma ng CWD ang paglabo · {actor}", "Gin-kumpirma han CWD an paglubog · {actor}"],
  ["event.deployed_priorities", "Priorities confirmed · {actor}", "Nakumpirma ang prayoridad · {actor}", "Nakumpirma an prayoridad · {actor}"],
  ["event.notified", "{n} households notified by app and SMS", "{n} pamilya ang naabisuhan sa app at SMS", "{n} nga pamilya an napahibaro ha app ngan SMS"],
  ["event.deployed_truck", "Truck water at {place}", "Tubig ng trak sa {place}", "Tubig han trak ha {place}"],
  ["event.resident_confirmed", "{n} residents confirmed water is back", "{n} residente ang nagkumpirmang bumalik ang tubig", "{n} nga residente an nag-kumpirma nga nabalik an tubig"],
  ["event.resolved", "Water restored · residents notified", "Bumalik ang tubig · naabisuhan ang residente", "Nabalik an tubig · napahibaro an residente"],
  ["record.alloc_title", "Allocation log", "Allocation log", "Allocation log"],
  ["record.alloc_sub", "Every decision, who made it, and when", "Bawat desisyon, sino ang gumawa, at kailan", "Kada desisyon, hin-o an naghimo, ngan san-o"],
  ["record.col_time", "Time", "Oras", "Oras"],
  ["record.col_decision", "Decision", "Desisyon", "Desisyon"],
  ["record.col_by", "By", "Ni", "Ni"],
  ["alloc.generated", "Recommended order generated from need and {jmp}-minute access", "Nabuo ang inirekomendang ayos mula sa pangangailangan at {jmp}-minutong access", "Nahimo an girekomenda nga han-ay tikang ha kinahanglan ngan {jmp}-minuto nga access"],
  ["alloc.confirmed", "Recommended order confirmed; trucks routed to {first} first", "Nakumpirma ang ayos; unang pinadalhan ng trak ang {first}", "Nakumpirma an han-ay; siyahan nga ginpadad-an hin trak an {first}"],
  ["alloc.moved", "{name} moved from #{from} to #{to}: {reason}", "Inilipat ang {name} mula #{from} sa #{to}: {reason}", "Ginbalhin an {name} tikang #{from} ngadto #{to}: {reason}"],
  ["alloc.closed", "Event closed; trucks released", "Sarado ang event; pinauwi ang trak", "Sirado an event; ginpauli an trak"],
  ["alloc.system", "System", "System", "System"],
  ["record.hours_title", "Hours without piped water in {year}", "Oras na walang tubig sa tubo noong {year}", "Oras nga waray tubig ha tubo han {year}"],
  ["record.hours_sub", "Affected barangays, all causes", "Apektadong barangay, lahat ng sanhi", "Apektado nga barangay, ngatanan nga hinungdan"],
  ["record.carry_title", "Carry this into the next event", "Dalhin ito sa susunod na event", "Darha ini ha sunod nga event"],
  ["record.carry_body", "Turbidity passed the plant limit about an hour after catchment rain reached {mm} mm. Next time, pre-alert {places} the moment rain reaches {mm} mm, before the plant has to cut back.", "Lumampas sa limit ang turbidity mga isang oras matapos umabot sa {mm} mm ang ulan. Sa susunod, abisuhan agad ang {places} pag umabot sa {mm} mm ang ulan, bago magbawas ang planta.", "Linmapos ha limit an turbidity mga usa ka oras katapos umabot ha {mm} mm an uran. Ha sunod, pahibaroa dayon an {places} kun umabot ha {mm} mm an uran, antes magkunhod an planta."],
  ["record.add_rule", "Add as an early-warning rule", "Idagdag bilang maagang babala", "Idugang sugad nga temprano nga pahimangno"],
  ["record.not_now", "Not now", "Hindi muna", "Diri anay"],
  ["record.sample", "Sample data throughout.", "Sample data ang lahat.", "Sample data an ngatanan."],

  // Resident / captain confirmation (spec 06 AC3–AC4)
  ["confirm.title_resident", "Is water back at your tap?", "Bumalik na ba ang tubig sa gripo mo?", "Nabalik na ba an tubig ha imo gripo?"],
  ["confirm.title_captain", "Is water back in {barangay}?", "Bumalik na ba ang tubig sa {barangay}?", "Nabalik na ba an tubig ha {barangay}?"],
  ["confirm.yes", "Yes, it's back", "Oo, bumalik na", "Oo, nabalik na"],
  ["confirm.no", "Still no water", "Wala pa ring tubig", "Waray pa gihapon tubig"],
  ["confirm.sent_yes", "Thanks. Sent to the LGU.", "Salamat. Naipadala na sa LGU.", "Salamat. Naipadara na ha LGU."],
  ["confirm.sent_no", "Sent. The LGU will put your barangay back on the priority list.", "Naipadala na. Ibabalik ng LGU ang barangay mo sa listahan ng prayoridad.", "Naipadara na. Ibabalik han LGU an imo barangay ha listahan han prayoridad."],

  // Water's back (spec 06 resolved state, wireframe p.6)
  ["back.time", "Back at {time}", "Bumalik {time}", "Nabalik {time}"],
  ["back.earlier", "{n} minutes earlier", "{n} minutong mas maaga", "{n} minuto nga mas temprano"],
  ["back.later", "{n} minutes later", "{n} minutong mas huli", "{n} minuto nga mas ulahi"],
  ["back.vs_rest", " than our best estimate of {time}. Off for {duration}.", " kaysa sa tantiya naming {time}. Nawala nang {duration}.", " kaysa han amon banabana nga {time}. Nawara hin {duration}."],
  ["back.headline", "Water's back.", "Bumalik na ang tubig.", "Nabalik na an tubig."],
  ["back.sub", "You were ready all day.", "Handa ka buong araw.", "Andam ka bug-os nga adlaw."],
  ["back.tip_run", "Let the tap run until the water is clear before drinking.", "Padaluyin muna ang gripo hanggang luminaw bago inumin.", "Pabay-i anay nga magawas an gripo tubtob tumin-aw antes imnon."],
  ["back.tip_keep", "Keep your {litres} L for one more day, then use it for washing.", "Itabi ang {litres} L ng isa pang araw, saka gamitin panghugas.", "Tipigi an {litres} L hin usa pa ka adlaw, katapos gamita panhugas."],
  ["back.captain", "{name} checked your sources {n} times today.", "{n} beses sinuri ni {name} ang mga mapagkukunan ngayon.", "{n} ka beses gin-check ni {name} an mga kuhaan yana."],
  ["back.captain_reach", "{name}'s updates sent {n} households in {barangay} to working water.", "Dahil sa update ni {name}, {n} pamilya sa {barangay} ang nakakuha ng tubig.", "Tungod han update ni {name}, {n} nga pamilya ha {barangay} an nakakuha hin tubig."],
  ["back.thanks", "Say thanks to {name}", "Magpasalamat kay {name}", "Pagpasalamat kan {name}"],
  ["operator.sample", "Sample data. The charts, detector and sample readings on this screen are not from the server.", "Sample data. Ang mga chart, detector at sample na reading dito ay hindi galing sa server.", "Sample data. An mga chart, detector ngan sample nga reading dinhi diri tikang ha server."],
  ["lgu.event_pill_closed", "Closed event {id} · {cause}", "Closed event {id} · {cause}", "Closed event {id} · {cause}"],
  ["lgu.none_value", "None yet", "None yet", "None yet"],
  ["lgu.live_flagged", "Flagged by the predictor at {time}", "Flagged by the predictor at {time}", "Flagged by the predictor at {time}"],
  ["lgu.result_ok", "Saved {saved} barangay priorities. Residents were notified in the app in {notified} barangays.", "Saved {saved} barangay priorities. Residents were notified in the app in {notified} barangays.", "Saved {saved} barangay priorities. Residents were notified in the app in {notified} barangays."],
  ["lgu.result_partial", "Priorities saved for {saved} barangays, but notifying residents failed, so nothing reached residents yet. {reason}", "Priorities saved for {saved} barangays, but notifying residents failed, so nothing reached residents yet. {reason}", "Priorities saved for {saved} barangays, but notifying residents failed, so nothing reached residents yet. {reason}"],
  ["lgu.result_error", "Nothing was saved. {reason}", "Nothing was saved. {reason}", "Nothing was saved. {reason}"],
  ["lgu.decision_done_body_live", "Residents were notified in the app. Watch their answers on the live board.", "Residents were notified in the app. Watch their answers on the live board.", "Residents were notified in the app. Watch their answers on the live board."],
  ["lgu.decision_partial_body", "Priorities are saved. Residents have not been notified yet.", "Priorities are saved. Residents have not been notified yet.", "Priorities are saved. Residents have not been notified yet."],
  ["lgu.window_span","{from} to {to}","{from} to {to}","{from} to {to}"],
  // Operator "why" panel (spec 02 drivers / operator_actions). Operator screens are staff-facing. DRAFT FIL/WAR: native review.
  ["why.title", "Plant risk", "Plant risk", "Plant risk"],
  ["why.as_of", "As of {time}", "Hanggang {time}", "Tubtob {time}"],
  ["why.signal", "Signal {level} of 4", "Signal {level} sa 4", "Signal {level} han 4"],
  ["why.p_turbidity", "Turbidity risk", "Panganib ng labo", "Peligro han lubog"],
  ["why.p_drought", "Drought risk", "Panganib ng tagtuyot", "Peligro han hulaw"],
  ["why.fallback", "WSP rule fired (not a model score)", "Umandar ang WSP rule (hindi score ng modelo)", "Nagana an WSP rule (diri score han modelo)"],
  ["why.actions_title", "What to do now", "Ano ang gagawin ngayon", "Ano an buhaton yana"],
  ["why.no_actions", "No action needed at this signal level.", "Walang kailangang gawin sa signal na ito.", "Waray kinahanglan buhaton hini nga signal."],
  // Scorecard (lib/scorecard.ts). English in every column until translated: staff screen.
  ["why.scope_note", "Whole plant, not one intake.", "Whole plant, not one intake.", "Whole plant, not one intake."],
  ["why.band_0", "Low", "Low", "Low"],
  ["why.band_1", "Guarded", "Guarded", "Guarded"],
  ["why.band_2", "Elevated", "Elevated", "Elevated"],
  ["why.band_3", "High", "High", "High"],
  ["why.band_4", "Very high", "Very high", "Very high"],
  ["why.horizon_turbidity", "next 48 h", "next 48 h", "next 48 h"],
  ["why.horizon_drought", "next 7 days", "next 7 days", "next 7 days"],
  ["why.score_title", "Why it's {band}", "Why it's {band}", "Why it's {band}"],
  ["why.points", "{points} points", "{points} points", "{points} points"],
  ["why.start_turbidity", "Starting point: clear water, no rain", "Starting point: clear water, no rain", "Starting point: clear water, no rain"],
  ["why.start_drought", "Starting point: empty reservoir, no rain", "Starting point: empty reservoir, no rain", "Starting point: empty reservoir, no rain"],
  ["why.total", "Total", "Total", "Total"],
  ["why.rule_raised", "A WSP rule raised the level to {band}. The model alone says {model_band}.", "A WSP rule raised the level to {band}. The model alone says {model_band}.", "A WSP rule raised the level to {band}. The model alone says {model_band}."],
  ["why.without_title", "What would change it", "What would change it", "What would change it"],
  ["why.without_row", "Without {input}: {band}", "Without {input}: {band}", "Without {input}: {band}"],
  ["why.without_none", "No single input would lower the level on its own.", "No single input would lower the level on its own.", "No single input would lower the level on its own."],
  ["why.how_title", "How this is calculated", "How this is calculated", "How this is calculated"],
  ["why.how_body", "A logistic model with four inputs. Score = 50 + 10 × log-odds: 50 is even odds, and each input adds or removes points from the starting point. The level cut-offs are the same ones the system uses everywhere. Trained on synthetic incidents built on real 2016–2025 Catbalogan rain, not real incident history. Scores rank risk; they are not calibrated probabilities.", "A logistic model with four inputs. Score = 50 + 10 × log-odds: 50 is even odds, and each input adds or removes points from the starting point. The level cut-offs are the same ones the system uses everywhere. Trained on synthetic incidents built on real 2016–2025 Catbalogan rain, not real incident history. Scores rank risk; they are not calibrated probabilities.", "A logistic model with four inputs. Score = 50 + 10 × log-odds: 50 is even odds, and each input adds or removes points from the starting point. The level cut-offs are the same ones the system uses everywhere. Trained on synthetic incidents built on real 2016–2025 Catbalogan rain, not real incident history. Scores rank risk; they are not calibrated probabilities."],
  ["why.top_rule", "A WSP rule fired on a measured reading", "A WSP rule fired on a measured reading", "A WSP rule fired on a measured reading"],
  ["why.top_input", "Mostly: {input}", "Mostly: {input}", "Mostly: {input}"],
  ["why.details", "See why, and every action", "See why, and every action", "See why, and every action"],
  ["why.details_more", "See why, and {n} more actions", "See why, and {n} more actions", "See why, and {n} more actions"],
  ["risk.title", "Turbidity and drought predictions", "Turbidity and drought predictions", "Turbidity and drought predictions"],
  ["risk.signal_note", "The signal is the higher of the two levels.", "The signal is the higher of the two levels.", "The signal is the higher of the two levels."],
  ["risk.sets_signal", "Sets the signal", "Sets the signal", "Sets the signal"],
  ["trend.now", "Now", "Now", "Now"],
  ["trend.time", "Time", "Time", "Time"],
  ["trend.title", "How the risk built up", "How the risk built up", "How the risk built up"],
  ["trend.subtitle", "Last 48 hours, hour by hour.", "Last 48 hours, hour by hour.", "Last 48 hours, hour by hour."],
  ["trend.hours_ago", "{n} h ago", "{n} h ago", "{n} h ago"],
  ["trend.reached", "{band} for {n} h", "{band} for {n} h", "{band} for {n} h"],
  ["trend.rising", "Rising", "Rising", "Rising"],
  ["trend.easing", "Easing", "Easing", "Easing"],
  ["trend.steady", "Steady", "Steady", "Steady"],
  ["trend.at_level_for", "{band} for the last {n} h", "{band} for the last {n} h", "{band} for the last {n} h"],
  ["trend.caption", "Shaded bands are the signal levels, calm blue at Low to coral at Very high. Hover for the exact scores.", "Shaded bands are the signal levels, calm blue at Low to coral at Very high. Hover for the exact scores.", "Shaded bands are the signal levels, calm blue at Low to coral at Very high. Hover for the exact scores."],
  ["why.score_title_model", "Why {risk} is {band}", "Why {risk} is {band}", "Why {risk} is {band}"],
  ["why.score_sub", "Each input adds or removes points from the starting point; the total sets the level.", "Each input adds or removes points from the starting point; the total sets the level.", "Each input adds or removes points from the starting point; the total sets the level."],
  ["why.kept_low", "Kept low by: {input}", "Kept low by: {input}", "Kept low by: {input}"],
  ["trend.all_window", "{band} all 48 h", "{band} all 48 h", "{band} all 48 h"],
  ["trend.sample_note", "Sample trend: the model run hourly on sample readings.", "Sample trend: the model run hourly on sample readings.", "Sample trend: the model run hourly on sample readings."],
  ["risk.unavailable", "No prediction to explain yet. The deployed predictor does not return its reasons; redeploy disruption-predictor.", "No prediction to explain yet. The deployed predictor does not return its reasons; redeploy disruption-predictor.", "No prediction to explain yet. The deployed predictor does not return its reasons; redeploy disruption-predictor."],
  ["why.chart_label", "Score chart: starts at {start}, ends at {total} ({band})", "Score chart: starts at {start}, ends at {total} ({band})", "Score chart: starts at {start}, ends at {total} ({band})"],
  ["why.bar_tooltip", "{input}: {points} points, from {from} to {to}", "{input}: {points} points, from {from} to {to}", "{input}: {points} points, from {from} to {to}"],
  ["why.cutoffs", "Levels: Guarded from {l1} · Elevated {l2} · High {l3} · Very high {l4}.", "Levels: Guarded from {l1} · Elevated {l2} · High {l3} · Very high {l4}.", "Levels: Guarded from {l1} · Elevated {l2} · High {l3} · Very high {l4}."],
  ["why.chart_caption", "Each bar moves the score on from the row above; shaded bands are the levels.", "Each bar moves the score on from the row above; shaded bands are the levels.", "Each bar moves the score on from the row above; shaded bands are the levels."],
  ["why.f_turbidity_ntu", "Raw turbidity, Kulador", "Raw turbidity, Kulador", "Raw turbidity, Kulador"],
  ["why.f_rain_24h_mm", "Rain, last 24 h", "Rain, last 24 h", "Rain, last 24 h"],
  ["why.f_rain_72h_mm", "Rain, last 72 h", "Rain, last 72 h", "Rain, last 72 h"],
  ["why.f_forecast_rain_48h_mm", "Forecast rain, next 48 h", "Forecast rain, next 48 h", "Forecast rain, next 48 h"],
  ["why.f_reservoir_pct", "Reservoir level", "Reservoir level", "Reservoir level"],
  ["why.f_rain_14d_mm", "Rain, last 14 days", "Rain, last 14 days", "Rain, last 14 days"],
  ["why.f_rain_30d_mm", "Rain, last 30 days", "Rain, last 30 days", "Rain, last 30 days"],
  ["why.f_days_since_rain_over_5mm", "Days since 5 mm of rain", "Days since 5 mm of rain", "Days since 5 mm of rain"],
  ["why.src_logged", "logged reading", "logged reading", "logged reading"],
  ["why.src_rain", "Open-Meteo rain", "Open-Meteo rain", "Open-Meteo rain"],
  ["why.src_forecast_live", "Open-Meteo forecast, can be wrong", "Open-Meteo forecast, can be wrong", "Open-Meteo forecast, can be wrong"],
  ["why.src_forecast_seeded", "seeded forecast, can be wrong", "seeded forecast, can be wrong", "seeded forecast, can be wrong"],
  ["why.src_forecast_missing", "no forecast available", "no forecast available", "no forecast available"],

  // Demo phone (/demo/phone): presenter-facing handset mockup. DRAFT FIL/WAR: native review.
  ["phone.title", "Demo phone", "Demo na telepono", "Demo nga telepono"],
  ["phone.sender", "Resident phone", "Telepono ng residente", "Telepono han residente"],
  ["phone.inbox_empty", "No messages yet. They appear here when the backend sends an SMS.", "Wala pang mensahe. Lalabas dito kapag may SMS na ipinadala ang backend.", "Waray pa mensahe. Makita dinhi kun may SMS nga ginpadara an backend."],
  ["phone.dry_run", "dry run", "pagsubok lang", "pagsulay la"],
  ["phone.live", "live", "live", "live"],
  ["phone.sending", "Sending…", "Ipinapadala…", "Ginpapadara…"],
  ["phone.send", "Send", "Ipadala", "Ipadara"],
  ["phone.type", "Type a reply", "Mag-type ng sagot", "Mag-type hin sabat"],
  ["phone.needs_keys", "Live mode is off. This phone needs the Supabase keys (VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in apps/web/.env.local) to receive and send SMS.", "Naka-off ang live mode. Kailangan ng telepono ang mga Supabase key (VITE_SUPABASE_URL at VITE_SUPABASE_ANON_KEY sa apps/web/.env.local) para tumanggap at magpadala ng SMS.", "Naka-off an live mode. Kinahanglan han telepono an mga Supabase key (VITE_SUPABASE_URL ngan VITE_SUPABASE_ANON_KEY ha apps/web/.env.local) para makarawat ngan makapadara hin SMS."],
  ["phone.reply_failed", "The reply did not go through: {error}", "Hindi naipadala ang sagot: {error}", "Diri naipadara an sabat: {error}"],
  ["phone.realtime_off", "Live updates are reconnecting. Messages may be late.", "Kumokonekta ulit ang live updates. Maaaring huli ang mensahe.", "Nag-konekta utro an live updates. Basi ulahi an mensahe."],

  // Sample / live labelling (Dev A). DRAFT FIL/WAR: native review.
  ["sample.chip", "Sample", "Halimbawa", "Halimbawa"],
  ["sample.note", "Sample data, not from the server", "Halimbawang data, hindi galing sa server", "Halimbawa nga data, diri tikang ha server"],
  // Storage plan timing + captain checklist, derived from the heads-up rule and the disruption times. DRAFT FIL/WAR: native review.
  ["storage.rule", "{litres} L = {people} people × {per} L each, the same rule as the heads-up SMS.", "{litres} L = {people} tao × {per} L bawat isa, kapareho ng patakaran sa SMS na paalala.", "{litres} L = {people} nga tawo × {per} L kada usa, pareho han patakaran han SMS nga pahinumdom."],
  ["storage.timing_likely", "Water is likely to stop from {time}. Fill your containers before then.", "Posibleng mawala ang tubig simula {time}. Punuin ang mga lalagyan bago nito.", "Posible mawara an tubig tikang {time}. Pun-a an mga lalagyan antes hito."],
  ["storage.timing_window", "Expected back {window}.", "Inaasahang babalik {window}.", "Ginlalaoman nga mabalik {window}."],
  ["captain.checklist_title", "Suggested checklist", "Mungkahing checklist", "Gisuhestiyon nga checklist"],
  ["captain.checklist_note", "Based on the current status. Ticks stay on this phone only.", "Batay sa kasalukuyang status. Sa teleponong ito lang nananatili ang mga tsek.", "Based ha karuyag nga status. Ha telepono la ini nga nagtitikod an mga tsek."],
  ["captain.check.notify_vulnerable", "Tell vulnerable households to store water", "Sabihan ang mga bulnerableng pamilya na mag-ipon ng tubig", "Pasabti an mga bulnerable nga pamilya nga mag-ipon hin tubig"],
  ["captain.check.containers", "Check the communal containers are full", "Tingnan kung puno ang mga pampublikong lalagyan", "Kitaa kun puno an mga pampubliko nga lalagyan"],
  ["captain.check.coordinate", "Coordinate with {name}, the first stop for your barangay", "Makipag-ugnayan sa {name}, ang unang mapagkukunan ng barangay", "Pakig-ugnay ha {name}, an una nga kuhaan han barangay"],
  ["captain.check.coordinate_any", "Coordinate with the nearest backup source", "Makipag-ugnayan sa pinakamalapit na reserbang mapagkukunan", "Pakig-ugnay ha pinakamalapit nga reserba nga kuhaan"],
  ["captain.check.update_households", "Update households when the time window changes", "I-update ang mga pamilya kapag nagbago ang oras", "I-update an mga pamilya kun mag-ilis an oras"],
  ["captain.check.collect_thanks", "Collect thank-yous from households", "Kolektahin ang pasasalamat ng mga pamilya", "Pagkolekta hin pasasalamat han mga pamilya"],
  ["captain.check.round", "Do the morning round of your sources", "Gawin ang pag-ikot sa umaga sa mga mapagkukunan", "Buhata an paglibot ha aga ha mga kuhaan"],
  // LGU screens (English only by spec 08).
  ["lgu.no_data", "Not in the backend yet", "Not in the backend yet", "Not in the backend yet"],
  ["lgu.flagged_n", "{n} barangays flagged", "{n} barangays flagged", "{n} barangays flagged"],
  ["lgu.sample_route_note", "Sample figures. Trucks and partners are not in the backend yet.", "Sample figures. Trucks and partners are not in the backend yet.", "Sample figures. Trucks and partners are not in the backend yet."],
  ["lgu.sample_types_note", "Only residential is live. LGU facilities come from barangays.critical_facilities; commercial and industrial need CWD billing classes.", "Only residential is live. LGU facilities come from barangays.critical_facilities; commercial and industrial need CWD billing classes.", "Only residential is live. LGU facilities come from barangays.critical_facilities; commercial and industrial need CWD billing classes."],
  // Live event record (/lgu/event). English only by spec 08.
  ["lgu.affected_sub_live", "{barangays} barangays", "{barangays} barangays", "{barangays} barangays"],
  ["evrec.open_badge", "Open since {time}", "Open since {time}", "Open since {time}"],
  ["evrec.resolved_badge", "Resolved {time}", "Resolved {time}", "Resolved {time}"],
  ["evrec.title", "Event {id}: {cause}", "Event {id}: {cause}", "Event {id}: {cause}"],
  ["evrec.subtitle", "{day}. Started {time} (Asia/Manila).", "{day}. Started {time} (Asia/Manila).", "{day}. Started {time} (Asia/Manila)."],
  ["evrec.live_note", "Live from the backend: disruptions, event_log, allocations, continuity chains and sms_outbox. It refreshes when a new event arrives.", "Live from the backend: disruptions, event_log, allocations, continuity chains and sms_outbox. It refreshes when a new event arrives.", "Live from the backend: disruptions, event_log, allocations, continuity chains and sms_outbox. It refreshes when a new event arrives."],
  ["evrec.none_title", "No disruption recorded yet", "No disruption recorded yet", "No disruption recorded yet"],
  ["evrec.none_body", "When the predictor opens a disruption, its record appears here.", "When the predictor opens a disruption, its record appears here.", "When the predictor opens a disruption, its record appears here."],
  ["evrec.stage.predicted", "Predicted", "Predicted", "Predicted"],
  ["evrec.stage.heads_up", "Heads-up", "Heads-up", "Heads-up"],
  ["evrec.stage.confirmed", "Confirmed", "Confirmed", "Confirmed"],
  ["evrec.stage.deployed", "Deployed", "Deployed", "Deployed"],
  ["evrec.stage.notified", "Notified", "Notified", "Notified"],
  ["evrec.stage.resident_confirmed", "Residents confirmed", "Residents confirmed", "Residents confirmed"],
  ["evrec.stage.resolved", "Resolved", "Resolved", "Resolved"],
  ["evrec.stage_pending", "Not yet", "Not yet", "Not yet"],
  ["evrec.stage_events", "{n} events", "{n} events", "{n} events"],
  ["evrec.stat_duration", "Duration", "Duration", "Duration"],
  ["evrec.stat_open", "Still open", "Still open", "Still open"],
  ["evrec.stat_barangays", "Barangays notified", "Barangays notified", "Barangays notified"],
  ["evrec.stat_allocated", "Allocations", "Allocations", "Allocations"],
  ["evrec.stat_overrides", "Overrides", "Overrides", "Overrides"],
  ["evrec.stat_sms", "SMS sent", "SMS sent", "SMS sent"],
  ["evrec.timeline_title", "What happened", "What happened", "What happened"],
  ["evrec.timeline_sub", "Every event_log row, oldest first. Times in Asia/Manila.", "Every event_log row, oldest first. Times in Asia/Manila.", "Every event_log row, oldest first. Times in Asia/Manila."],
  ["evrec.timeline_empty", "No events yet.", "No events yet.", "No events yet."],
  ["evrec.all_barangays", "All served barangays", "All served barangays", "All served barangays"],
  ["evrec.system", "system", "system", "system"],
  ["evrec.by", "by {actor}", "by {actor}", "by {actor}"],
  ["evrec.d.heads_up", "Level {level} · {n} SMS recipients · {mode}", "Level {level} · {n} SMS recipients · {mode}", "Level {level} · {n} SMS recipients · {mode}"],
  ["evrec.d.allocation", "Priority {rank}", "Priority {rank}", "Priority {rank}"],
  ["evrec.d.override", "Priority {rank}, moved from suggested {from}", "Priority {rank}, moved from suggested {from}", "Priority {rank}, moved from suggested {from}"],
  ["evrec.d.source", "Source: {name}", "Source: {name}", "Source: {name}"],
  ["evrec.d.off_chain", "not on the ranked chain", "not on the ranked chain", "not on the ranked chain"],
  ["evrec.d.notified", "Notified via {channels}", "Notified via {channels}", "Notified via {channels}"],
  ["evrec.d.restored", "Confirmed water is back", "Confirmed water is back", "Confirmed water is back"],
  ["evrec.d.not_restored", "Reported water NOT back", "Reported water NOT back", "Reported water NOT back"],
  ["evrec.d.resolved", "All notified barangays restored", "All notified barangays restored", "All notified barangays restored"],
  ["evrec.alloc_title", "Allocation log", "Allocation log", "Allocation log"],
  ["evrec.alloc_sub", "The order the officer confirmed (allocations table)", "The order the officer confirmed (allocations table)", "The order the officer confirmed (allocations table)"],
  ["evrec.alloc_empty", "No allocation confirmed yet.", "No allocation confirmed yet.", "No allocation confirmed yet."],
  ["evrec.col_time", "Time", "Time", "Time"],
  ["evrec.col_rank", "Priority", "Priority", "Priority"],
  ["evrec.col_barangay", "Barangay", "Barangay", "Barangay"],
  ["evrec.col_first_stop", "First stop", "First stop", "First stop"],
  ["evrec.col_decision", "Decision", "Decision", "Decision"],
  ["evrec.col_by", "By", "By", "By"],
  ["evrec.col_sms", "SMS", "SMS", "SMS"],
  ["evrec.followed", "Followed the suggested order", "Followed the suggested order", "Followed the suggested order"],
  ["evrec.overridden", "Overridden: suggested {from}, set to {rank}", "Overridden: suggested {from}, set to {rank}", "Overridden: suggested {from}, set to {rank}"],
  ["evrec.no_chain", "no chain yet", "no chain yet", "no chain yet"],
  ["evrec.sms_title", "SMS", "SMS", "SMS"],
  ["evrec.sms_sub", "Masked numbers only (sms_outbox)", "Masked numbers only (sms_outbox)", "Masked numbers only (sms_outbox)"],
  ["evrec.sms_totals", "{out} sent · {in} replies", "{out} sent · {in} replies", "{out} sent · {in} replies"],
  ["evrec.sms_modes", "{dry} dry run · {live} live", "{dry} dry run · {live} live", "{dry} dry run · {live} live"],
  ["evrec.sms_none", "No SMS logged for this event.", "No SMS logged for this event.", "No SMS logged for this event."],
  ["evrec.sms_unavailable", "The SMS log is not on this project yet (sms_outbox).", "The SMS log is not on this project yet (sms_outbox).", "The SMS log is not on this project yet (sms_outbox)."],
] as const;

export type CopyKeyName = (typeof ROWS)[number][0];

export const COPY: CopyKey[] = ROWS.map(([key, english, filipino, waray]) =>
  CopyKey.parse({ key, english, filipino, waray }),
);

export const COPY_BY_KEY = new Map(COPY.map((row) => [row.key, row]));

// Spec 08: strings the team isn't sure of. Today that's every Waray and Filipino draft.
export const NEEDS_REVIEW = { waray: "all", filipino: "all" } as const;
