// SPEC: 08 — the one trilingual CopyKey table. Every user-facing string lives here.
// Rows are [key, english, filipino, waray]. {placeholders} are filled by t().
//
// REVIEW: every Waray string and every Filipino string is a draft by the dev team,
// not a native-speaker review. Spec 08 says flag, don't guess: they're all listed in
// NEEDS_REVIEW below until a fluent teammate checks them. English is the default
// language until then.
import { CopyKey } from "../contracts/spec08";

const ROWS = [
  // App shell
  ["app.name", "Tubig Patas", "Tubig Patas", "Tubig Patas"],
  ["app.saved_offline", "Saved on this phone · works without signal", "Naka-save sa phone na ito · gumagana kahit walang signal", "Naka-save hini nga phone · nagana bisan waray signal"],
  ["app.offline_stale", "No signal · showing what was saved at {time}", "Walang signal · ipinapakita ang naka-save noong {time}", "Waray signal · ginpapakita an naka-save han {time}"],
  ["app.loading", "Getting the latest status…", "Kinukuha ang pinakabagong balita…", "Ginkukuha an pinakabag-o nga kahimtang…"],
  ["app.error_title", "We can't reach Tubig Patas right now", "Hindi namin maabot ang Tubig Patas ngayon", "Diri namon maabot an Tubig Patas yana"],
  ["app.error_body", "Check your signal, then try again.", "Tingnan ang signal, saka subukan ulit.", "Kitaa an signal, katapos utroha."],
  ["app.retry", "Try again", "Subukan ulit", "Utroha"],
  ["app.updated_at", "Updated {time}", "Na-update {time}", "Gin-update {time}"],
  ["app.back", "Back", "Bumalik", "Balik"],

  // Resident bottom bar
  ["nav.status", "Status", "Status", "Kahimtang"],
  ["nav.sources", "Sources", "Mapagkukunan", "Kuhaan"],
  ["nav.history", "History", "Kasaysayan", "Kasaysayan"],

  // Water states (signal level → state, see lib/waterState.ts)
  ["state.flowing.chip", "Flowing", "Dumadaloy", "Nagawas"],
  ["state.flowing.headline", "Water is flowing", "May tubig", "May tubig"],
  ["state.flowing.sub", "Next planned work: none", "Susunod na nakaplanong trabaho: wala", "Sunod nga plano nga trabaho: waray"],
  ["state.headsup.chip", "Heads-up", "Paalala", "Pahinumdom"],
  ["state.headsup.headline", "Store water tonight", "Mag-ipon ng tubig ngayong gabi", "Pag-ipon hin tubig yana nga gab-i"],
  ["state.headsup.sub", "Likely to stop from {time}", "Posibleng mawala simula {time}", "Posible mawara tikang {time}"],
  ["state.interrupted.chip", "Interrupted", "Naputol", "Naputol"],
  ["state.interrupted.headline", "No water from the tap", "Walang tubig sa gripo", "Waray tubig ha gripo"],
  ["state.repair.chip", "Planned repair", "Nakaplanong ayos", "Plano nga pag-ayad"],
  ["state.repair.headline", "Off for a pipe repair", "Patay dahil sa pag-aayos ng tubo", "Patay kay ginaayad an tubo"],
  ["cause.turbidity", "The river is too muddy to treat after last night's rain.", "Sobrang labo ng ilog para linisin dahil sa ulan kagabi.", "Sobra kalubog an salog para limpyohan tungod han uran kagab-i."],
  ["cause.drought", "The river is too low to supply everyone.", "Masyadong mababa ang ilog para sa lahat.", "Sobra kahubas an salog para ha ngatanan."],
  ["cause.repair", "The pipes are being repaired.", "Inaayos ang mga tubo.", "Ginaayad an mga tubo."],
  ["cause_short.turbidity", "river too muddy to treat", "sobrang labo ng ilog", "sobra kalubog an salog"],
  ["cause_short.drought", "river too low", "masyadong mababa ang ilog", "sobra kahubas an salog"],
  ["cause_short.repair", "pipe repair", "pag-aayos ng tubo", "pag-ayad han tubo"],

  // Resident status card
  ["status.back_between", "Back today between", "Babalik ngayong araw sa pagitan ng", "Mabalik yana nga adlaw butnga han"],
  ["status.most_likely", "Most likely", "Malamang", "Posible gud"],
  ["status.now", "Now", "Ngayon", "Yana"],
  ["status.back", "Back", "Balik", "Balik"],
  ["status.scale_6am", "6 AM", "6 AM", "6 AM"],
  ["status.scale_noon", "Noon", "Tanghali", "Udto"],
  ["status.scale_6pm", "6 PM", "6 PM", "6 PM"],
  ["status.scale_12am", "12 AM", "12 AM", "12 AM"],
  ["status.next_update_by", "Next update by {time}", "Susunod na update bago mag-{time}", "Sunod nga update antes han {time}"],
  ["status.next_update_rest", ", even if nothing changes.", ", kahit walang pagbabago.", ", bisan waray pagbag-o."],
  ["action.store_water", "Store water", "Mag-ipon ng tubig", "Pag-ipon hin tubig"],
  ["action.find_water", "Find water", "Maghanap ng tubig", "Pangita hin tubig"],

  // Storage plan
  ["storage.title", "Store {litres} L for 24 hours", "Mag-ipon ng {litres} L para sa 24 oras", "Pag-ipon hin {litres} L para ha 24 oras"],
  ["storage.household", "For your household of {people} · {per} L per person", "Para sa pamilya ng {people} · {per} L bawat tao", "Para ha pamilya nga {people} · {per} L kada tawo"],
  ["storage.steps", "{done} of {total} steps done", "{done} sa {total} hakbang tapos na", "{done} han {total} nga lakang human na"],
  ["storage.litres", "{have} of {target} L", "{have} sa {target} L", "{have} han {target} L"],
  ["storage.alerts_title", "Alerts are on", "Naka-on ang alerto", "Naka-on an alerto"],
  ["storage.alerts_body", "You'll hear from us by app and SMS", "Makakatanggap ka ng balita sa app at SMS", "Makakarawat ka hin balita ha app ngan SMS"],
  ["storage.container", "Container {n}", "Lalagyan {n}", "Butangan {n}"],
  ["storage.container_litres", "{litres} L", "{litres} L", "{litres} L"],
  ["storage.container_full", "Container {n}, full", "Lalagyan {n}, puno na", "Butangan {n}, puno na"],
  ["storage.hint", "Tap a container when it's full. Fill now, while there's still pressure in the line.", "Pindutin ang lalagyan kapag puno na. Mag-ipon na habang malakas pa ang tulo.", "Pinduta an butangan kun puno na. Pag-ipon na samtang makusog pa an tubig ha tubo."],
  ["storage.done", "That's enough for 24 hours. No need to store more.", "Sapat na iyan para sa 24 oras. Hindi na kailangang mag-ipon pa.", "Igo na iton para ha 24 oras. Diri na kinahanglan mag-ipon pa."],

  // Backup sources
  ["runout.title", "If you run out", "Kung maubusan ka", "Kun maubusan ka"],
  ["runout.nearest", "Plan {letter} · nearest", "Plan {letter} · pinakamalapit", "Plan {letter} · pinakahirani"],
  ["runout.see_all", "See all {n} backup sources", "Tingnan ang {n} na reserbang mapagkukunan", "Kitaa an {n} nga reserba nga kuhaan"],
  ["source.safe", "Safe to drink", "Ligtas inumin", "Luwas imnon"],
  ["source.boil", "Boil before drinking", "Pakuluan bago inumin", "Pabukala antes imnon"],
  ["source.washing", "Washing only", "Panghugas lang", "Panhugas la"],
  ["source.walk", "{n} min walk", "{n} minutong lakad", "{n} minuto nga lakat"],
  ["source.free", "Free", "Libre", "Libre"],
  ["source.cost", "₱{price} per {litres} L", "₱{price} bawat {litres} L", "₱{price} kada {litres} L"],
  ["source.checked_by", "Checked by {name}, barangay water captain · {time}", "Sinuri ni {name}, barangay water captain · {time}", "Gin-check ni {name}, barangay water captain · {time}"],
  ["source.reported", "{name} · {time}", "{name} · {time}", "{name} · {time}"],
  ["source.live.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["source.live.open_stock", "Open · has stock", "Bukas · may stock", "Bukas · may stock"],
  ["source.live.queue", "Flowing · queue of ~{n}", "Dumadaloy · pila ng ~{n}", "Nagawas · linya nga ~{n}"],
  ["source.live.scheduled", "Scheduled {time}", "Nakaiskedyul {time}", "Naka-iskedyul {time}"],
  ["source.live.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["source.live.dry", "Dry", "Tuyo", "Hubas"],
  ["source.bring", "Bring containers", "Magdala ng lalagyan", "Pagdara hin butangan"],
  ["sources.title", "Your backup water plan", "Ang iyong reserbang plano sa tubig", "An imo reserba nga plano ha tubig"],
  ["sources.sub", "{barangay}. Ranked by safety first, then walking time, then cost.", "{barangay}. Inayos ayon sa kaligtasan, saka layo ng lakad, saka presyo.", "{barangay}. Ginhan-ay sumala han kaluwasan, katapos kahirayo han lakat, katapos presyo."],
  ["sources.legend_a", "Bars show the full round trip, queue included. The mark is ", "Ipinapakita ng guhit ang buong balikan, kasama ang pila. Ang marka ay ", "Ginpapakita han linya an bug-os nga balikan, upod an linya. An marka amo an "],
  ["sources.legend_b", "{min} minutes", "{min} minuto", "{min} minuto"],
  ["sources.legend_c", ", the WHO/UNICEF line for basic access.", ", ang pamantayan ng WHO/UNICEF para sa batayang access.", ", an sukol han WHO/UNICEF para ha basic nga access."],
  ["sources.plan_label", "Plan {letter}:", "Plan {letter}:", "Plan {letter}:"],
  ["sources.round_trip", "Round trip ≈ {n} min", "Balikan ≈ {n} min", "Balikan ≈ {n} min"],
  ["sources.over_line", "Round trip ≈ {n} min, over the {jmp}-min line", "Balikan ≈ {n} min, lampas sa {jmp}-min na guhit", "Balikan ≈ {n} min, labaw ha {jmp}-min nga linya"],

  // History tab (no wireframe yet)
  ["history.title", "History", "Kasaysayan", "Kasaysayan"],
  ["history.empty", "Past interruptions in your barangay will show here.", "Dito makikita ang mga nakaraang pagkawala ng tubig sa barangay mo.", "Dinhi makikita an mga naglabay nga pagkawara han tubig ha imo barangay."],

  // Barangay + language picker
  ["settings.title", "Your barangay", "Ang iyong barangay", "An imo barangay"],
  ["settings.sub", "We'll remember it on this phone.", "Tatandaan namin ito sa phone na ito.", "Hinunumdoman namon ini hini nga phone."],
  ["settings.language", "Language", "Wika", "Yinaknan"],
  ["settings.save", "Save", "I-save", "I-save"],
  ["lang.waray", "Waray", "Waray", "Waray"],
  ["lang.filipino", "Filipino", "Filipino", "Filipino"],
  ["lang.english", "English", "English", "English"],

  // Barangay water captain
  ["captain.role", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}", "Barangay water captain · {barangay}"],
  ["captain.greeting_morning", "Good morning, {name}", "Magandang umaga, {name}", "Maupay nga aga, {name}"],
  ["captain.greeting_afternoon", "Good afternoon, {name}", "Magandang hapon, {name}", "Maupay nga kulop, {name}"],
  ["captain.greeting_evening", "Good evening, {name}", "Magandang gabi, {name}", "Maupay nga gab-i, {name}"],
  ["captain.up_to_date", "Up to date · {time}", "Updated · {time}", "Updated · {time}"],
  ["captain.works_offline", "Keeps working without signal", "Gumagana kahit walang signal", "Nagana bisan waray signal"],
  ["captain.piped_off", "Piped water is off", "Patay ang tubig sa tubo", "Patay an tubig ha tubo"],
  ["captain.piped_on", "Piped water is on", "May tubig sa tubo", "May tubig ha tubo"],
  ["captain.since", "Since {time} · {cause}", "Mula {time} · {cause}", "Tikang {time} · {cause}"],
  ["captain.expected_back", "Expected back", "Inaasahang babalik", "Ginlalaoman nga mabalik"],
  ["captain.relies_on", "Your barangay relies on", "Umaasa ang barangay mo sa", "Nasandig an imo barangay ha"],
  ["captain.n_sources", "{n} sources", "{n} mapagkukunan", "{n} nga kuhaan"],
  ["captain.round_title", "Morning round", "Pag-ikot sa umaga", "Paglibot ha aga"],
  ["captain.round_progress", "{done} of {total} checked", "{done} sa {total} nasuri", "{done} han {total} na-check"],
  ["captain.checked_at", "Checked {time}", "Nasuri {time}", "Na-check {time}"],
  ["captain.not_checked", "Not checked", "Hindi pa nasusuri", "Diri pa na-check"],
  ["captain.plan_line", "Plan {letter} · {safety}", "Plan {letter} · {safety}", "Plan {letter} · {safety}"],
  ["captain.toast", "Sent to {n} households", "Naipadala sa {n} na pamilya", "Ginpadara ha {n} nga pamilya"],
  ["captain.updates_title", "Your updates today", "Ang iyong mga update ngayon", "An imo mga update yana"],
  ["captain.delivered", "updates delivered", "update na naihatid", "update nga naihatod"],
  ["captain.to_working", "went to a working source", "pumunta sa gumaganang mapagkukunan", "kinadto ha nagana nga kuhaan"],
  ["captain.more_thanks", "+ {n} more thank-yous", "+ {n} pang pasasalamat", "+ {n} pa nga salamat"],
  ["seg.flowing", "Flowing", "Dumadaloy", "Nagawas"],
  ["seg.long_queue", "Long queue", "Mahabang pila", "Haluag nga linya"],
  ["seg.dry", "Dry", "Tuyo", "Hubas"],

  // CWD operator dashboard
  ["operator.org", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant", "Catbalogan Water District · Treatment plant"],
  ["operator.tab_monitor", "Monitor", "Monitor", "Monitor"],
  ["operator.tab_log", "Readings log", "Talaan ng readings", "Listahan han readings"],
  ["operator.tab_events", "Events", "Mga pangyayari", "Mga hitabo"],
  ["operator.tab_thresholds", "Thresholds", "Mga hangganan", "Mga utlan"],
  ["operator.shift", "Shift: {name} · {hours}", "Shift: {name} · {hours}", "Shift: {name} · {hours}"],
  ["operator.title", "Antiao intake · {day} {time}", "Antiao intake · {day} {time}", "Antiao intake · {day} {time}"],
  ["operator.event_open", "Event {id} open", "Bukas ang event {id}", "Bukas an event {id}"],
  ["operator.readings_pill", "Plant readings", "Readings ng planta", "Readings han planta"],
  ["operator.readings_sub", "Logged by you, hourly", "Ikaw ang nagtatala, kada oras", "Ikaw an nagsusurat, kada oras"],
  ["operator.readings_due", "Last {last} · {due} due", "Huli {last} · {due} ang susunod", "Katapusan {last} · {due} an sunod"],
  ["operator.rain_pill", "Rainfall over the catchment", "Ulan sa catchment", "Uran ha catchment"],
  ["operator.rain_sub", "Open-Meteo, automatic", "Open-Meteo, awtomatiko", "Open-Meteo, awtomatiko"],
  ["operator.raw", "Raw turbidity", "Raw turbidity", "Raw turbidity"],
  ["operator.over_limit", "Over limit", "Lampas sa limit", "Labaw ha limit"],
  ["operator.raw_over", "Above the {limit} plant limit since {time}", "Lampas sa {limit} na limit ng planta mula {time}", "Labaw ha {limit} nga limit han planta tikang {time}"],
  ["operator.raw_under", "Under the {limit} plant limit", "Mas mababa sa {limit} na limit ng planta", "Ubos han {limit} nga limit han planta"],
  ["operator.treated", "Treated turbidity", "Treated turbidity", "Treated turbidity"],
  ["operator.treated_under", "Under the {limit} NTU limit", "Mas mababa sa {limit} NTU na limit", "Ubos han {limit} NTU nga limit"],
  ["operator.treated_over", "Over the {limit} NTU limit", "Lampas sa {limit} NTU na limit", "Labaw ha {limit} NTU nga limit"],
  ["operator.clarifier", "Clarifier flow", "Daloy ng clarifier", "Agos han clarifier"],
  ["operator.clarifier_cut", "Capacity ≈ {cap} L/s · cut back", "Kapasidad ≈ {cap} L/s · binawasan", "Kapasidad ≈ {cap} L/s · ginkunhuran"],
  ["operator.clarifier_full", "Capacity ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s", "Kapasidad ≈ {cap} L/s"],
  ["operator.reservoir", "Reservoir", "Reservoir", "Reservoir"],
  ["operator.reservoir_trend", "Falling ~{n} points an hour", "Bumababa ~{n} puntos kada oras", "Nauubos ~{n} puntos kada oras"],
  ["unit.ntu", "NTU", "NTU", "NTU"],
  ["unit.lps", "L/s", "L/s", "L/s"],
  ["unit.pct", "%", "%", "%"],
  ["operator.chart_turbidity", "Raw turbidity, last 24 hours", "Raw turbidity, nakaraang 24 oras", "Raw turbidity, naglabay nga 24 oras"],
  ["operator.chart_units", "NTU · hourly", "NTU · kada oras", "NTU · kada oras"],
  ["operator.plant_limit", "Plant limit {limit} NTU", "Limit ng planta {limit} NTU", "Limit han planta {limit} NTU"],
  ["operator.now_value", "{value} now", "{value} ngayon", "{value} yana"],
  ["operator.chart_rain", "Rainfall over the Antiao catchment", "Ulan sa Antiao catchment", "Uran ha Antiao catchment"],
  ["operator.rain_summary", "mm per hour · {mm} mm since {time} · {days} dry-spell days", "mm kada oras · {mm} mm mula {time} · {days} araw na tagtuyot", "mm kada oras · {mm} mm tikang {time} · {days} ka adlaw nga hulaw"],
  ["operator.log_title", "Log the {time} reading", "Itala ang reading ng {time}", "Isurat an reading han {time}"],
  ["operator.last_logged", "Last logged {time} by you", "Huling naitala {time} mo", "Katapusan nga ginsurat {time} nimo"],
  ["operator.field_raw", "Raw turbidity (NTU)", "Raw turbidity (NTU)", "Raw turbidity (NTU)"],
  ["operator.field_treated", "Treated turbidity (NTU)", "Treated turbidity (NTU)", "Treated turbidity (NTU)"],
  ["operator.field_clarifier", "Clarifier flow (L/s)", "Daloy ng clarifier (L/s)", "Agos han clarifier (L/s)"],
  ["operator.field_reservoir", "Reservoir (%)", "Reservoir (%)", "Reservoir (%)"],
  ["operator.field_status", "Plant status", "Kalagayan ng planta", "Kahimtang han planta"],
  ["plant.normal", "Normal", "Normal", "Normal"],
  ["plant.degraded", "Reduced output", "Bawas na output", "Gin-kunhuran nga output"],
  ["plant.shutdown", "Shut down", "Nakasara", "Sirado"],
  ["operator.save", "Save reading", "I-save ang reading", "I-save an reading"],
  ["operator.save_hint", "Saves offline if the plant connection drops.", "Nase-save offline kapag nawala ang koneksyon ng planta.", "Nase-save offline kun mawara an koneksyon han planta."],
  ["operator.saved", "Saved on this device. {n} waiting to send.", "Naka-save sa device na ito. {n} naghihintay maipadala.", "Naka-save hini nga device. {n} naghuhulat ipadara."],
  ["operator.invalid", "Check the highlighted numbers.", "Suriin ang mga numerong naka-highlight.", "I-check an mga numero nga naka-highlight."],
  ["operator.err_number", "Enter a number, 0 or more", "Maglagay ng numero, 0 pataas", "Pagbutang hin numero, 0 pataas"],
  ["operator.err_pct", "Enter a number from 0 to 100", "Maglagay ng numero mula 0 hanggang 100", "Pagbutang hin numero tikang 0 tubtob 100"],
  ["detector.label", "Disruption detector", "Disruption detector", "Disruption detector"],
  ["detector.turbidity", "Turbidity spike", "Biglang paglabo", "Kalit nga paglubog"],
  ["detector.matched", "{n} of {total} signals match. You confirmed it at {time}.", "{n} sa {total} senyales ang tugma. Kinumpirma mo ito noong {time}.", "{n} han {total} nga senyales an tugma. Gin-kumpirma mo ini han {time}."],
  ["detector.sig_raw", "Raw turbidity above {limit} NTU since {time}", "Raw turbidity lampas {limit} NTU mula {time}", "Raw turbidity labaw {limit} NTU tikang {time}"],
  ["detector.sig_rain", "{mm} mm of rain in {hours} hours over the catchment", "{mm} mm na ulan sa loob ng {hours} oras sa catchment", "{mm} mm nga uran ha sulod han {hours} oras ha catchment"],
  ["detector.sig_clarifier", "Clarifier cut from {from} to {to} L/s", "Clarifier binawasan mula {from} hanggang {to} L/s", "Clarifier ginkunhuran tikang {from} ngadto {to} L/s"],
  ["detector.low_source", "Low source level", "Mababang lebel ng pinagkukunan", "Ubos nga lebel han kuhaan"],
  ["detector.low_source_note", "{n} of {total} · no dry spell, intake normal", "{n} sa {total} · walang tagtuyot, normal ang intake", "{n} han {total} · waray hulaw, normal an intake"],
  ["detector.repair", "Repair work", "Pag-aayos", "Pag-ayad"],
  ["detector.repair_note", "{n} of {total} · nothing scheduled", "{n} sa {total} · walang nakaiskedyul", "{n} han {total} · waray naka-iskedyul"],
  ["detector.window", "Time window residents see", "Oras na nakikita ng mga residente", "Oras nga nakikita han mga residente"],
  ["detector.window_value", "{window} · likely {likely}", "{window} · malamang {likely}", "{window} · posible {likely}"],
  ["detector.adjust", "Adjust", "Baguhin", "Igbag-o"],
  ["detector.next", "Next resident update due {time}. You'll be reminded at {remind}.", "Susunod na update sa residente bago mag-{time}. Ipapaalala sa iyo sa {remind}.", "Sunod nga update ha residente antes han {time}. Pahinumdoman ka ha {remind}."],
  ["warnings.title", "Your early warnings", "Ang iyong maagang babala", "An imo temprano nga pahimangno"],
  ["warnings.sub", "How much notice your flags gave residents before taps ran dry", "Gaano kaaga nabalitaan ng mga residente bago naubos ang tubig", "Pira ka temprano nabaltakan an mga residente antes nahubsan an gripo"],
  ["warnings.turbidity", "turbidity", "labo", "lubog"],
  ["warnings.repair", "pipe repair", "ayos ng tubo", "pag-ayad han tubo"],
  ["warnings.low_source", "low source", "mababang pinagkukunan", "ubos nga kuhaan"],
  ["warnings.note", "All three confirmed by the LGU after the event closed.", "Kinumpirma ng LGU ang tatlo matapos ang event.", "Gin-kumpirma han LGU an tulo katapos han event."],
  ["operator.footnote", "Thresholds from the CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Confirm they are current before launch. Readings shown are sample data.", "Mga hangganan mula sa CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Kumpirmahin bago ilunsad. Sample data ang mga reading.", "Mga utlan tikang ha CWD 2022 Water Safety Plan: {warn} NTU treated, {shut} NTU raw, ≈{cap} L/s clarifier. Kumpirmaha antes ilunsad. Sample data an mga reading."],

  // Admin placeholder (spec 07)
  ["admin.org", "Catbalogan CDRRMO", "Catbalogan CDRRMO", "Catbalogan CDRRMO"],
  ["admin.placeholder_title", "LGU dashboard", "LGU dashboard", "LGU dashboard"],
  ["admin.placeholder_body", "The allocation and event screens come next, in specs 06 and 07.", "Susunod ang allocation at event screens, sa specs 06 at 07.", "Sunod an allocation ngan event screens, ha specs 06 ngan 07."],
] as const;

export type CopyKeyName = (typeof ROWS)[number][0];

export const COPY: CopyKey[] = ROWS.map(([key, english, filipino, waray]) =>
  CopyKey.parse({ key, english, filipino, waray }),
);

export const COPY_BY_KEY = new Map(COPY.map((row) => [row.key, row]));

// Spec 08: strings the team isn't sure of. Today that's every Waray and Filipino draft.
export const NEEDS_REVIEW = { waray: "all", filipino: "all" } as const;
